export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  date: string;
  category: string;
  readingTime: string;
  image: string;
}

export const blogPosts: BlogPost[] = [
  {
    slug: "best-free-online-tools-2026",
    title: "Best Free Online Tools 2026: 140+ Tools for Every Task",
    description: "Complete guide to the best free online tools in 2026. 140+ tools for PDF, Image, Text, Developer, AI Writing, and more. No signup, no limits.",
    date: "July 14, 2026",
    category: "Guide",
    readingTime: "15 min",
    image: "/images/blog/home.png",
  },
  {
    slug: "free-grammarly-alternative-offline",
    title: "Free Grammarly Alternative That Works Offline in 2026",
    description: "Find the best free Grammarly alternative that works offline. Compare top grammar checkers including Krynn Tools, LanguageTool, and QuillBot.",
    date: "July 14, 2026",
    category: "AI Writing",
    readingTime: "10 min",
    image: "/images/blog/grammar-fixer.png",
  },
  {
    slug: "smallpdf-vs-ilovepdf-vs-krynn-tools",
    title: "Smallpdf vs iLovePDF vs Krynn Tools: Which Is Best in 2026?",
    description: "Compare Smallpdf, iLovePDF, and Krynn Tools across price, features, privacy, and limits. Find the best free PDF tool for your needs.",
    date: "July 14, 2026",
    category: "PDF",
    readingTime: "12 min",
    image: "/images/blog/compress-pdf.png",
  },
  {
    slug: "remove-background-image-free-2026",
    title: "How to Remove Background from Image Free in 2026 (No Upload)",
    description: "Learn how to remove photo backgrounds for free without uploading to servers. Compare the best free background removers in 2026.",
    date: "July 14, 2026",
    category: "Image",
    readingTime: "8 min",
    image: "/images/blog/remove-background.png",
  },
  {
    slug: "best-free-image-upscaler-2026",
    title: "Best Free Image Upscaler 2026: Enlarge Photos Without Losing Quality",
    description: "Compare the best free image upscalers in 2026. Learn how AI upscaling works and enlarge photos up to 4x without losing quality.",
    date: "July 14, 2026",
    category: "Image",
    readingTime: "9 min",
    image: "/images/blog/image-upscaler.png",
  },
  {
    slug: "best-free-qr-code-generator-2026",
    title: "Best Free QR Code Generator 2026: Custom Colors, Logos & More",
    description: "Compare the best free QR code generators in 2026. Create custom QR codes with colors, logos, and high-resolution download for print.",
    date: "July 14, 2026",
    category: "Security",
    readingTime: "8 min",
    image: "/images/blog/qr-code-generator.png",
  },
  {
    slug: "convert-png-to-jpg-free",
    title: "How to Convert PNG to JPG Free Online (Batch Convert)",
    description: "Convert PNG to JPG for free online. Batch convert multiple images, adjust quality, and reduce file size instantly. No signup required.",
    date: "July 14, 2026",
    category: "Image",
    readingTime: "6 min",
    image: "/images/blog/png-to-jpg.png",
  },
  {
    slug: "best-free-resume-builder-2026",
    title: "Best Free Resume Builder 2026: 5 Templates That Get Interviews",
    description: "Build a professional resume for free in 2026. Compare the best free resume builders with ATS-friendly templates and PDF download.",
    date: "July 14, 2026",
    category: "Career",
    readingTime: "10 min",
    image: "/images/blog/resume-builder.png",
  },
  {
    slug: "how-to-compress-pdf-without-losing-quality",
    title: "How to Compress a PDF Without Losing Quality",
    description: "Learn how to compress PDF files without losing quality. Free client-side tool for fast, secure PDF optimization.",
    date: "January 15, 2026",
    category: "PDF",
    readingTime: "7 min",
    image: "/images/blog/compress-pdf.png",
  },
  {
    slug: "how-to-merge-multiple-pdfs",
    title: "How to Merge Multiple PDFs Into One File for Free",
    description: "Learn how to merge multiple PDF files into a single document for free. Client-side processing keeps your files private.",
    date: "January 20, 2026",
    category: "PDF",
    readingTime: "6 min",
    image: "/images/blog/merge-pdf.png",
  },
  {
    slug: "10-signs-your-password-isnt-strong-enough",
    title: "10 Signs Your Password Isn't Strong Enough",
    description: "Is your password really protecting you? Learn 10 warning signs that your passwords need an upgrade.",
    date: "January 25, 2026",
    category: "Security",
    readingTime: "8 min",
    image: "/images/blog/password-generator.png",
  },
  {
    slug: "qr-codes-explained-static-vs-dynamic",
    title: "QR Codes Explained: Static vs Dynamic",
    description: "Understand the difference between static and dynamic QR codes, when to use each, and how to generate them for free.",
    date: "January 30, 2026",
    category: "Security",
    readingTime: "6 min",
    image: "/images/blog/qr-code-generator.png",
  },
  {
    slug: "best-practices-for-qr-code-design",
    title: "Best Practices for QR Code Design",
    description: "Learn QR code design best practices for print and digital. Ensure scannability with size, contrast, error correction, and branding tips.",
    date: "March 1, 2026",
    category: "Security",
    readingTime: "7 min",
    image: "/images/blog/qr-code-generator.png",
  },
  {
    slug: "how-to-generate-qr-codes-for-business",
    title: "How to Generate QR Codes for Business",
    description: "Create QR codes for menus, events, payments, and marketing. Step-by-step guide for business owners.",
    date: "March 5, 2026",
    category: "Security",
    readingTime: "6 min",
    image: "/images/blog/qr-code-generator.png",
  },
  {
    slug: "understanding-error-correction-in-qr-codes",
    title: "Understanding Error Correction in QR Codes",
    description: "Learn how QR code error correction works (L, M, Q, H levels) and why it matters for durability and design.",
    date: "March 10, 2026",
    category: "Security",
    readingTime: "7 min",
    image: "/images/blog/qr-code-generator.png",
  },
  {
    slug: "how-to-shrink-image-file-size",
    title: "How to Shrink Image File Size Without Losing Quality",
    description: "Learn how to shrink image file sizes for web, email, and social media without losing visible quality.",
    date: "February 1, 2026",
    category: "Image",
    readingTime: "7 min",
    image: "/images/blog/compress-image.png",
  },
  {
    slug: "how-to-remove-background-from-photo",
    title: "How to Remove a Background From a Photo in 10 Seconds",
    description: "Remove photo backgrounds instantly with a free browser-based tool. No software install, no upload required.",
    date: "February 5, 2026",
    category: "Image",
    readingTime: "5 min",
    image: "/images/blog/remove-background.png",
  },
  {
    slug: "json-formatting-best-practices",
    title: "JSON Formatting Best Practices for Developers",
    description: "Master JSON formatting with best practices for indentation, naming, validation, and tooling.",
    date: "February 10, 2026",
    category: "Developer",
    readingTime: "8 min",
    image: "/images/blog/json-formatter.png",
  },
  {
    slug: "what-is-base64-encoding",
    title: "What Is Base64 Encoding and When Do You Need It?",
    description: "Understand Base64 encoding, how it works, and when you actually need to use it. Practical examples for developers.",
    date: "February 15, 2026",
    category: "Developer",
    readingTime: "7 min",
    image: "/images/blog/base64-encoder.png",
  },
  {
    slug: "bmi-explained-what-numbers-mean",
    title: "BMI Explained: What the Numbers Actually Mean",
    description: "Understand BMI categories, how to calculate yours, and what the numbers really tell you about your health.",
    date: "February 20, 2026",
    category: "Health",
    readingTime: "6 min",
    image: "/images/blog/bmi-calculator.png",
  },
  {
    slug: "how-emi-is-calculated-on-loan",
    title: "How EMI Is Calculated on a Loan (With Formula)",
    description: "Understand how loan EMI is calculated with the reducing balance formula. Includes examples and a free calculator.",
    date: "February 25, 2026",
    category: "Finance",
    readingTime: "8 min",
    image: "/images/blog/loan-emi-calculator.png",
  },
  {
    slug: "how-to-extract-text-from-scanned-pdfs",
    title: "How to Extract Text from Scanned PDFs",
    description: "Learn how to extract text from scanned PDFs using free client-side OCR. Step-by-step guide with privacy-first processing.",
    date: "July 12, 2026",
    category: "PDF",
    readingTime: "6 min",
    image: "/images/blog/compress-pdf.png",
  },
  {
    slug: "best-free-dice-roller-for-board-games",
    title: "Best Free Dice Roller for Board Games",
    description: "Find the best free online dice roller for board games and tabletop RPGs. Roll D4, D6, D8, D10, D12, D20 with realistic animations.",
    date: "July 12, 2026",
    category: "Misc",
    readingTime: "5 min",
    image: "/images/blog/home.png",
  },
  {
    slug: "how-to-crop-passport-size-photos-online",
    title: "How to Crop Passport Size Photos Online",
    description: "Learn how to crop passport size photos online for free. Includes US, UK, India, and other country-specific photo dimensions.",
    date: "July 12, 2026",
    category: "Image",
    readingTime: "6 min",
    image: "/images/blog/compress-image.png",
  },
  {
    slug: "how-to-generate-strong-passwords-online",
    title: "How to Generate a Strong Password Online",
    description: "Learn how to generate strong, random passwords online. Free tool creates secure passwords with customizable length and character rules.",
    date: "July 12, 2026",
    category: "Security",
    readingTime: "7 min",
    image: "/images/blog/password-generator.png",
  },
  {
    slug: "how-to-convert-text-case-online",
    title: "How to Convert Text Case Online",
    description: "Convert text between UPPERCASE, lowercase, Title Case, and Sentence case instantly. Free online case converter tool.",
    date: "July 12, 2026",
    category: "Text",
    readingTime: "5 min",
    image: "/images/blog/case-converter.png",
  },
  {
    slug: "how-to-resize-images-for-social-media",
    title: "How to Resize Images for Every Social Media Platform",
    description: "Resize images for Instagram, Facebook, Twitter, YouTube, and LinkedIn with correct dimensions. Free social media image resizer.",
    date: "July 12, 2026",
    category: "Social Media",
    readingTime: "7 min",
    image: "/images/blog/social-image-resizer.png",
  },
  {
    slug: "what-is-a-uuid-and-how-to-generate-one",
    title: "What Is a UUID and How to Generate One",
    description: "Understand UUID v4 identifiers, when to use them, and how to generate unique IDs for your applications.",
    date: "July 12, 2026",
    category: "Developer",
    readingTime: "6 min",
    image: "/images/blog/uuid-generator.png",
  },
  {
    slug: "how-to-calculate-percentage-online",
    title: "How to Calculate Percentage Online",
    description: "Learn how to calculate percentages, percentage increase, decrease, and difference. Free online percentage calculator with examples.",
    date: "July 12, 2026",
    category: "Calculators",
    readingTime: "6 min",
    image: "/images/blog/percentage-calculator.png",
  },
  {
    slug: "how-to-convert-units-online",
    title: "How to Convert Units Online",
    description: "Convert between metric and imperial units for length, weight, temperature, volume, and area. Free online unit converter.",
    date: "July 12, 2026",
    category: "Calculators",
    readingTime: "7 min",
    image: "/images/blog/unit-converter.png",
  },
  {
    slug: "how-to-checksum-a-file",
    title: "How to Checksum a File (MD5, SHA-256)",
    description: "Verify file integrity by computing MD5, SHA-256, and SHA-512 checksums. Free online file checksum calculator.",
    date: "July 12, 2026",
    category: "Misc",
    readingTime: "5 min",
    image: "/images/blog/file-checksum-calculator.png",
  },
  {
    slug: "how-to-count-words-and-characters-online",
    title: "How to Count Words and Characters Online",
    description: "Count words, characters, sentences, and paragraphs in any text instantly. Free online word counter and character counter.",
    date: "July 12, 2026",
    category: "Text",
    readingTime: "5 min",
    image: "/images/blog/word-counter.png",
  },
];
