import { fuzzyScore } from './fuzzy-search';

export interface Tool {
  slug: string;
  name: string;
  description: string;
  category: string;
  categorySlug: string;
  icon: string;
  keywords: string[];
  popular?: boolean;
}

export interface Category {
  name: string;
  slug: string;
  description: string;
  icon: string;
  color: string;
}

export const categories: Category[] = [
  { name: "PDF Tools", slug: "pdf", description: "Compress, merge, split, convert, crop, watermark, and edit PDF files online for free.", icon: "FileText", color: "#EF4444" },
  { name: "Image Tools", slug: "image", description: "Compress, resize, convert, and edit images without uploading to a server.", icon: "Image", color: "#3B82F6" },
  { name: "Text Tools", slug: "text", description: "Count words, convert case, sort text, generate content, and more.", icon: "Type", color: "#10B981" },
  { name: "Developer Tools", slug: "dev", description: "Format JSON, encode Base64, generate UUIDs, test regex, and more.", icon: "Code", color: "#8B5CF6" },
  { name: "Web Design Tools", slug: "design", description: "Generate CSS gradients, box shadows, color palettes, and more.", icon: "Palette", color: "#F59E0B" },
  { name: "Calculators", slug: "calculators", description: "BMI, age, percentage, EMI, unit converters, and more free calculators.", icon: "Calculator", color: "#06B6D4" },
  { name: "Security Tools", slug: "security", description: "Generate passwords, hashes, QR codes, and check password strength.", icon: "Shield", color: "#EC4899" },
  { name: "Misc Tools", slug: "misc", description: "Random numbers, dice roller, coin flip, barcode generator, and more.", icon: "Sparkles", color: "#6366F1" },
  { name: "Social Media Tools", slug: "social-media", description: "Character counters, image resizers, hashtag tools, and more for social media.", icon: "ShareNetwork", color: "#E8100A" },
  { name: "AI Writing Tools", slug: "ai-writing", description: "AI-powered writing assistants for essays, blogs, social posts, and more.", icon: "Pen", color: "#8B5CF6" },
];

export const tools: Tool[] = [
  // PDF Tools (21)
  { slug: "compress-pdf", name: "Compress PDF", description: "Reduce PDF file size online free without losing quality. 100% client-side processing.", category: "PDF Tools", categorySlug: "pdf", icon: "FileDown", keywords: ["compress pdf online", "reduce pdf file size", "pdf compressor free", "shrink pdf", "compres pdf", "make pdf smaller", "how to compress pdf online free", "best free pdf compressor tool", "compress pdf without software", "pdf size reducer"], popular: true },
  { slug: "pdf-to-word", name: "PDF to Word", description: "Convert PDF to Word DOCX documents online free while preserving formatting and layout.", category: "PDF Tools", categorySlug: "pdf", icon: "FileText", keywords: ["pdf to word converter", "pdf to docx online", "convert pdf to word free", "pdf to doc", "pdf to word without software", "how to convert pdf to word online free", "best pdf to word converter", "pdf to editable word", "pdf to text converter"] },
  { slug: "word-to-pdf", name: "Word to PDF", description: "Convert Word documents to PDF format with perfect layout retention and formatting.", category: "PDF Tools", categorySlug: "pdf", icon: "FileType", keywords: ["word to pdf converter", "docx to pdf online", "convert word to pdf free", "doc to pdf", "word to pdf without software", "how to convert word to pdf online", "best free word to pdf tool", "microsoft word to pdf", "save word as pdf"] },
  { slug: "merge-pdf", name: "Merge PDF", description: "Combine multiple PDF files into a single document in any order you choose.", category: "PDF Tools", categorySlug: "pdf", icon: "Merge", keywords: ["merge pdf online", "combine pdf files", "join pdf documents", "merg pdf", "merge multiple pdfs", "how to combine pdf files online free", "best free pdf merger", "merge pdf without software", "pdf combiner tool"], popular: true },
  { slug: "split-pdf", name: "Split PDF", description: "Extract specific pages or ranges from a PDF into separate files instantly.", category: "PDF Tools", categorySlug: "pdf", icon: "Scissors", keywords: ["split pdf online", "extract pdf pages", "separate pdf pages", "spli pdf", "split pdf into pages", "how to split pdf online free", "best free pdf splitter", "extract pages from pdf", "divide pdf file"] },
  { slug: "rotate-pdf", name: "Rotate PDF", description: "Rotate all or selected PDF pages by 90, 180, or 270 degrees instantly.", category: "PDF Tools", categorySlug: "pdf", icon: "RotateCw", keywords: ["rotate pdf online", "flip pdf pages", "rotate pdf pages", "rotate pdf free", "how to rotate pdf pages online", "best pdf rotator tool", "rotate pdf 90 degrees", "flip pdf orientation"] },
  { slug: "delete-pdf-pages", name: "Delete PDF Pages", description: "Remove unwanted pages from a PDF file with a simple page selector and preview.", category: "PDF Tools", categorySlug: "pdf", icon: "Trash2", keywords: ["delete pdf pages", "remove pdf pages", "remove pages from pdf", "delete pages from pdf online", "how to remove pages from pdf free", "best tool to delete pdf pages", "pdf page remover"] },
  { slug: "protect-pdf", name: "Protect PDF", description: "Encrypt your PDF with a strong password to prevent unauthorized access and sharing.", category: "PDF Tools", categorySlug: "pdf", icon: "Shield", keywords: ["protect pdf with password", "add password to pdf", "encrypt pdf", "protct pdf", "lock pdf file", "how to password protect pdf online free", "best free pdf password protector", "secure pdf document"] },
  { slug: "unlock-pdf", name: "Unlock PDF", description: "Remove password protection from a locked PDF file for unrestricted viewing and editing.", category: "PDF Tools", categorySlug: "pdf", icon: "Unlock", keywords: ["unlock pdf", "remove pdf password", "decrypt pdf", "unlock pdf free", "how to unlock pdf online", "best free pdf unlocker", "remove pdf encryption", "open password protected pdf"] },
  { slug: "pdf-to-jpg", name: "PDF to JPG", description: "Convert each PDF page into a high-resolution JPG image for easy sharing and editing.", category: "PDF Tools", categorySlug: "pdf", icon: "Image", keywords: ["pdf to jpg converter", "pdf to image online", "pdf to jpeg free", "pdf to jpg", "how to convert pdf to jpg online free", "best free pdf to image converter", "pdf to png converter", "pdf page to image"], popular: true },
  { slug: "jpg-to-pdf", name: "JPG to PDF", description: "Turn JPG photos into a polished PDF document with adjustable page size and layout.", category: "PDF Tools", categorySlug: "pdf", icon: "FileImage", keywords: ["jpg to pdf converter", "image to pdf online", "jpeg to pdf free", "png to pdf", "how to convert jpg to pdf online free", "best free image to pdf converter", "photo to pdf", "multiple images to pdf"] },
  { slug: "excel-to-pdf", name: "Excel to PDF", description: "Export Excel spreadsheets to PDF with accurate table and chart rendering.", category: "PDF Tools", categorySlug: "pdf", icon: "Table", keywords: ["excel to pdf converter", "xlsx to pdf online", "spreadsheet to pdf", "xls to pdf", "how to convert excel to pdf online free", "best free excel to pdf tool", "excel sheet to pdf", "convert spreadsheet to pdf"] },
  { slug: "ppt-to-pdf", name: "PowerPoint to PDF", description: "Convert PowerPoint presentations to PDF while keeping slides and animations intact.", category: "PDF Tools", categorySlug: "pdf", icon: "Presentation", keywords: ["ppt to pdf converter", "powerpoint to pdf online", "slides to pdf", "pptx to pdf", "how to convert powerpoint to pdf free", "best free ppt to pdf converter", "presentation to pdf", "google slides to pdf"] },
  { slug: "extract-images-from-pdf", name: "Extract Images from PDF", description: "Pull out every embedded image from a PDF as individual files instantly.", category: "PDF Tools", categorySlug: "pdf", icon: "Images", keywords: ["extract images from pdf", "pdf image extractor", "get images from pdf", "rip images from pdf", "how to extract images from pdf online free", "best free pdf image extractor", "save images from pdf", "pdf picture extractor"] },
  { slug: "ocr-pdf", name: "OCR PDF", description: "Recognize and extract text from scanned PDFs and image-based documents using OCR technology.", category: "PDF Tools", categorySlug: "pdf", icon: "ScanText", keywords: ["ocr pdf", "text from scanned pdf", "pdf ocr online", "ocr pdf free", "how to extract text from scanned pdf", "best free pdf ocr tool", "scanned pdf to text", "pdf text recognizer"] },
  { slug: "rearrange-pdf", name: "Rearrange PDF Pages", description: "Drag and drop to reorder PDF pages in any sequence you want with a visual editor.", category: "PDF Tools", categorySlug: "pdf", icon: "ArrowsClockwise", keywords: ["rearrange pdf pages", "reorder pdf pages", "sort pdf pages", "change page order pdf", "rearrange pdf free", "how to reorder pdf pages online", "best free pdf page reordering tool", "drag drop pdf pages", "organize pdf pages"] },
  { slug: "crop-pdf", name: "Crop PDF", description: "Crop PDF pages by setting custom margin values to trim edges and adjust page layout.", category: "PDF Tools", categorySlug: "pdf", icon: "Crop", keywords: ["crop pdf", "trim pdf margins", "cut pdf edges", "crop pdf pages", "crop pdf free", "how to crop pdf pages online", "best free pdf cropping tool", "resize pdf page margins", "adjust pdf page size"] },
  { slug: "add-page-numbers", name: "Add Page Numbers", description: "Add page numbers to every page of your PDF with custom position, font, and style.", category: "PDF Tools", categorySlug: "pdf", icon: "ListOrdered", keywords: ["add page numbers to pdf", "number pdf pages", "page numbering pdf", "insert page numbers", "add page numbers free", "how to add page numbers to pdf online", "best free pdf page numbering tool", "pdf pagination"] },
  { slug: "add-watermark", name: "Add Watermark to PDF", description: "Overlay text watermarks on every page of your PDF with custom font, size, and opacity.", category: "PDF Tools", categorySlug: "pdf", icon: "Droplets", keywords: ["add watermark to pdf", "pdf watermark tool", "text watermark pdf", "stamp pdf", "watermark pdf free", "how to add watermark to pdf online", "best free pdf watermark tool", "pdf watermark creator", "overlay text on pdf"] },
  { slug: "repair-pdf", name: "Repair PDF", description: "Fix corrupted or damaged PDF files by re-encoding them with pdf-lib for recovery.", category: "PDF Tools", categorySlug: "pdf", icon: "Wrench", keywords: ["repair pdf", "fix corrupted pdf", "broken pdf repair", "restore pdf", "repair pdf free", "how to fix corrupted pdf online", "best free pdf repair tool", "recover damaged pdf", "pdf file recovery"] },
  { slug: "sign-pdf", name: "Sign PDF", description: "Add a signature image overlay to any page of your PDF document for electronic signing.", category: "PDF Tools", categorySlug: "pdf", icon: "Pen", keywords: ["sign pdf online", "add signature to pdf", "digital signature pdf", "electronically sign pdf", "sign pdf free", "how to sign pdf online free", "best free pdf signing tool", "e-sign pdf document", "pdf signature creator"] },
  { slug: "html-to-pdf", name: "HTML to PDF", description: "Convert HTML code or web pages into a downloadable PDF document instantly.", category: "PDF Tools", categorySlug: "pdf", icon: "Code", keywords: ["html to pdf converter", "convert html to pdf", "html to pdf online", "webpage to pdf", "html to pdf free", "how to convert html to pdf online", "best free html to pdf tool", "save webpage as pdf", "html to pdf javascript"] },

  // Image Tools (21)
  { slug: "compress-image", name: "Compress Image", description: "Shrink JPEG, PNG, and WebP file sizes while keeping visual quality high.", category: "Image Tools", categorySlug: "image", icon: "Minimize2", keywords: ["compress image online", "reduce image size", "image compressor free", "compres image", "make image smaller", "how to compress image online free", "best free image compressor", "jpg compressor", "png compressor", "webp compressor"], popular: true },
  { slug: "resize-image", name: "Resize Image", description: "Scale images to exact pixel dimensions or percentage with aspect ratio lock.", category: "Image Tools", categorySlug: "image", icon: "Maximize2", keywords: ["resize image online", "change image size", "image resizer free", "resze image", "resize photo online", "how to resize image online free", "best free image resizer", "scale image", "change photo dimensions"] },
  { slug: "crop-image", name: "Crop Image", description: "Trim unwanted areas from photos using preset or custom crop dimensions.", category: "Image Tools", categorySlug: "image", icon: "Crop", keywords: ["crop image online", "image cropper free", "photo crop tool", "crope image", "crop photo online", "how to crop image online free", "best free image cropper", "trim image", "cut image"] },
  { slug: "rotate-image", name: "Rotate Image", description: "Spin images to any angle or flip them horizontally and vertically.", category: "Image Tools", categorySlug: "image", icon: "RotateCw", keywords: ["rotate image online", "rotate photo free", "image rotator", "rotat image", "rotate picture online", "how to rotate image online free", "best free image rotator", "turn image", "rotate jpg"] },
  { slug: "flip-image", name: "Flip Image", description: "Mirror images horizontally or vertically to correct orientation issues.", category: "Image Tools", categorySlug: "image", icon: "FlipHorizontal", keywords: ["flip image online", "mirror image", "flip photo horizontally", "flip picture", "mirror photo online", "how to flip image online free", "best free image flipper", "reverse image horizontally", "flip image vertically"] },
  { slug: "png-to-jpg", name: "PNG to JPG", description: "Convert PNG images to lightweight JPG format with adjustable quality slider.", category: "Image Tools", categorySlug: "image", icon: "Minimize2", keywords: ["png to jpg converter", "convert png to jpeg online", "png to jpeg free", "png to jpg", "how to convert png to jpg online free", "best free png to jpg converter", "png to jpg without software", "change png to jpg"] },
  { slug: "jpg-to-png", name: "JPG to PNG", description: "Transform JPG photos into lossless PNG files with optional transparency support.", category: "Image Tools", categorySlug: "image", icon: "Maximize2", keywords: ["jpg to png converter", "convert jpeg to png online", "jpg to png free", "jpg to png", "how to convert jpg to png online free", "best free jpg to png converter", "jpeg to png", "change jpg to png"] },
  { slug: "webp-converter", name: "WEBP Converter", description: "Convert images to or from modern WebP format for faster web loading and storage.", category: "Image Tools", categorySlug: "image", icon: "RefreshCw", keywords: ["webp converter", "convert to webp online", "image to webp", "webp to jpg", "webp to png", "how to convert webp online free", "best free webp converter", "convert jpg to webp", "webp image converter"] },
  { slug: "svg-to-png", name: "SVG to PNG", description: "Rasterize vector SVG graphics into pixel-perfect PNG images at any resolution.", category: "Image Tools", categorySlug: "image", icon: "SvgToImg", keywords: ["svg to png converter", "convert svg to png", "svg to image", "svg to jpg", "how to convert svg to png online free", "best free svg converter", "vector to png", "svg rasterizer"] },
  { slug: "remove-background", name: "Remove Background", description: "Automatically strip backgrounds from photos to get clean transparent cutouts.", category: "Image Tools", categorySlug: "image", icon: "Eraser", keywords: ["remove background", "bg remover", "remove image background", "remove bg", "how to remove background from image free", "best free background remover", "transparent background maker", "cut out image background"], popular: true },
  { slug: "blur-image", name: "Blur Image", description: "Apply adjustable Gaussian blur to images for privacy protection or artistic effect.", category: "Image Tools", categorySlug: "image", icon: "Circle", keywords: ["blur image online", "image blur tool", "blur photo free", "blur picture", "how to blur image online free", "best free image blur tool", "gaussian blur photo", "soften image"] },
  { slug: "sharpen-image", name: "Sharpen Image", description: "Enhance blurry or soft images by boosting edge contrast and fine detail.", category: "Image Tools", categorySlug: "image", icon: "Focus", keywords: ["sharpen image online", "image sharpening tool", "unblur image", "sharpen photo", "how to sharpen image online free", "best free image sharpening tool", "enhance blurry photo", "fix blurry image"] },
  { slug: "watermark-image", name: "Watermark Image", description: "Overlay custom text or logo watermarks on photos to protect ownership and branding.", category: "Image Tools", categorySlug: "image", icon: "Droplets", keywords: ["add watermark to image", "image watermark tool", "watermark photo online", "watermark picture", "how to add watermark to image free", "best free image watermark tool", "photo watermark creator", "protect image with watermark"] },
  { slug: "add-text-to-image", name: "Add Text to Image", description: "Place styled text overlays on any image with custom font, color, and size controls.", category: "Image Tools", categorySlug: "image", icon: "Type", keywords: ["add text to image", "text overlay tool", "image text editor", "put text on image", "how to add text to photo online free", "best free text on image tool", "image text overlay maker", "caption image"] },
  { slug: "color-picker", name: "Image Color Picker", description: "Click anywhere on an image to extract its exact HEX, RGB, and HSL color values.", category: "Image Tools", categorySlug: "image", icon: "Pipette", keywords: ["color picker from image", "eyedropper tool", "extract color from image", "pick color from photo", "how to get color from image online free", "best free image color picker", "image color extractor", "hex color from image"] },
  { slug: "gif-to-jpg", name: "GIF to JPG", description: "Convert animated or static GIF images to high-quality JPG format instantly.", category: "Image Tools", categorySlug: "image", icon: "Image", keywords: ["gif to jpg converter", "convert gif to jpeg online", "gif to jpg free", "gif to jpg", "how to convert gif to jpg online free", "best free gif converter", "gif to png", "animated gif to jpg"] },
  { slug: "heic-converter", name: "HEIC Converter", description: "Convert Apple HEIC photos to JPG or PNG format for universal compatibility.", category: "Image Tools", categorySlug: "image", icon: "FileImage", keywords: ["heic converter", "heic to jpg", "convert heic online", "apple photo converter", "heic to png", "how to convert heic to jpg free", "best free heic converter", "iphone photo converter", "heic image converter"], popular: true },
  { slug: "tiff-converter", name: "TIFF Converter", description: "Convert TIFF images to JPG, PNG, or WebP format with quality controls.", category: "Image Tools", categorySlug: "image", icon: "Image", keywords: ["tiff converter", "tiff to jpg", "convert tiff online", "tiff to png", "how to convert tiff to jpg free", "best free tiff converter", "tiff image converter", "tiff to webp"] },
  { slug: "psd-converter", name: "PSD Converter", description: "Convert Photoshop PSD files to PNG, JPG, or WebP without Photoshop installed.", category: "Image Tools", categorySlug: "image", icon: "FileImage", keywords: ["psd converter", "psd to png", "convert psd online", "photoshop file converter", "psd to jpg", "how to convert psd to png free", "best free psd converter", "photoshop to png", "open psd without photoshop"] },
  { slug: "raw-converter", name: "RAW Converter", description: "Convert camera RAW files (CR2, NEF, ARW, DNG) to standard JPG or PNG images.", category: "Image Tools", categorySlug: "image", icon: "Camera", keywords: ["raw converter", "cr2 to jpg", "nef converter", "raw to jpg online", "raw to png", "how to convert raw to jpg free", "best free raw converter", "camera raw converter", "dng converter"] },
  { slug: "html-to-image", name: "HTML to Image", description: "Convert HTML code or web page snippets into downloadable PNG or JPG images.", category: "Image Tools", categorySlug: "image", icon: "Code", keywords: ["html to image converter", "html to png", "screenshot html code", "html to screenshot", "html to jpg", "how to convert html to image free", "best free html to image tool", "webpage to image", "html code to png"] },
  { slug: "meme-generator", name: "Meme Generator", description: "Create custom memes by adding top and bottom text to any image with styling options.", category: "Image Tools", categorySlug: "image", icon: "Smiley", keywords: ["meme generator online", "create meme free", "meme maker", "add text to meme", "make meme", "how to create meme online free", "best free meme generator", "meme creator tool", "custom meme maker"], popular: true },
  { slug: "image-upscaler", name: "Image Upscaler", description: "Enlarge images up to 4x while enhancing quality using AI-powered interpolation.", category: "Image Tools", categorySlug: "image", icon: "Maximize2", keywords: ["upscale image online", "image upscaler free", "enlarge image", "increase image resolution", "upscale photo", "how to enlarge image online free", "best free image upscaler", "ai image upscaler", "make image bigger"], popular: true },
  { slug: "ocr-image-to-text", name: "OCR Image to Text", description: "Extract text from images using OCR technology. Supports JPG, PNG, WebP, and BMP formats. 100% client-side.", category: "Image Tools", categorySlug: "image", icon: "ScanText", keywords: ["ocr image to text", "extract text from image", "image text recognizer", "ocr online free", "image ocr", "how to extract text from image free", "best free image ocr tool", "photo to text converter", "screenshot text extractor"] },

  // Text Tools (15)
  { slug: "word-counter", name: "Word Counter", description: "Instantly count words, characters, sentences, and paragraphs in any text with detailed stats.", category: "Text Tools", categorySlug: "text", icon: "Hash", keywords: ["word counter online", "character counter", "word count tool", "word countr", "how to count words online free", "best free word counter", "text word counter", "essay word count"], popular: true },
  { slug: "character-counter", name: "Character Counter", description: "Get detailed character stats including letters, digits, spaces, and whitespace counts.", category: "Text Tools", categorySlug: "text", icon: "Alphabet", keywords: ["character counter online", "text character count", "letter counter", "char counter", "how to count characters online free", "best free character counter", "character count tool", "text length counter"] },
  { slug: "case-converter", name: "Case Converter", description: "Switch text between UPPERCASE, lowercase, Title Case, and Sentence case instantly.", category: "Text Tools", categorySlug: "text", icon: "CaseSensitive", keywords: ["case converter online", "text case changer", "uppercase lowercase converter", "text case converter", "how to change text case online free", "best free case converter", "capitalize text tool", "lowercase converter"] },
  { slug: "remove-duplicate-lines", name: "Remove Duplicate Lines", description: "Strip out repeated lines from text while preserving original order and formatting.", category: "Text Tools", categorySlug: "text", icon: "ListMinus", keywords: ["remove duplicate lines", "delete duplicate text", "dedupe text online", "remove dupes", "how to remove duplicate lines free", "best free duplicate line remover", "text deduplicator", "remove repeated lines"] },
  { slug: "text-sorter", name: "Text Sorter", description: "Arrange lines alphabetically, reverse order, or numerically in one click.", category: "Text Tools", categorySlug: "text", icon: "ArrowUpDown", keywords: ["sort text online", "alphabetical sort tool", "sort lines of text", "text sorter free", "how to sort text lines online", "best free text sorting tool", "alphabetize lines", "sort list online"] },
  { slug: "reverse-text", name: "Reverse Text", description: "Reverse entire text strings, individual words, or character sequences instantly.", category: "Text Tools", categorySlug: "text", icon: "RotateCcw", keywords: ["reverse text online", "backwards text generator", "text reverser", "reverse string", "how to reverse text online free", "best free text reverser", "flip text backwards", "mirror text generator"] },
  { slug: "remove-extra-spaces", name: "Remove Extra Spaces", description: "Clean up double spaces, tabs, and trailing whitespace from any text automatically.", category: "Text Tools", categorySlug: "text", icon: "Space", keywords: ["remove extra spaces", "trim whitespace", "clean text spaces", "remove whitespace", "how to remove extra spaces online free", "best free whitespace remover", "text space cleaner", "remove blank spaces"] },
  { slug: "line-number-generator", name: "Line Number Generator", description: "Prepend sequential line numbers to every line of your pasted text or code.", category: "Text Tools", categorySlug: "text", icon: "ListOrdered", keywords: ["line number generator", "add line numbers", "number text lines", "number lines online", "how to add line numbers to text free", "best free line numbering tool", "code line numbers", "text line counter"] },
  { slug: "slug-generator", name: "Slug Generator", description: "Transform any text into a URL-safe slug with hyphens and lowercase letters for SEO.", category: "Text Tools", categorySlug: "text", icon: "Link", keywords: ["slug generator online", "url slug maker", "seo slug tool", "url slug generator", "how to create url slug online free", "best free slug generator", "permalink generator", "seo url maker"] },
  { slug: "lorem-ipsum-generator", name: "Lorem Ipsum Generator", description: "Generate realistic placeholder text with custom paragraph and word counts for design.", category: "Text Tools", categorySlug: "text", icon: "AlignLeft", keywords: ["lorem ipsum generator", "placeholder text generator", "dummy text", "lorem ipsum free", "how to generate lorem ipsum online", "best free lorem ipsum tool", "filler text generator", "sample text generator"] },
  { slug: "random-text-generator", name: "Random Text Generator", description: "Produce random words, sentences, or paragraphs for testing and mockups.", category: "Text Tools", categorySlug: "text", icon: "Shuffle", keywords: ["random text generator", "random words generator", "random sentence generator", "random paragraph generator", "how to generate random text online free", "best free random text tool", "lorem random", "sample text creator"] },
  { slug: "text-diff-checker", name: "Text Diff Checker", description: "Compare two text blocks side by side with highlighted additions and removals.", category: "Text Tools", categorySlug: "text", icon: "GitCompare", keywords: ["text diff checker", "compare texts online", "diff tool", "text comparison", "how to compare two texts online free", "best free text diff tool", "diff checker online", "side by side text compare"] },
  { slug: "html-encoder", name: "HTML Encoder", description: "Convert special characters to HTML entity codes for safe web embedding.", category: "Text Tools", categorySlug: "text", icon: "Code", keywords: ["html encoder online", "html entity encoder", "encode html entities", "html encode", "how to encode html entities free", "best free html encoder", "special character encoder", "html entity converter"] },
  { slug: "html-decoder", name: "HTML Decoder", description: "Translate HTML entity codes back into readable plain text characters instantly.", category: "Text Tools", categorySlug: "text", icon: "CodeXml", keywords: ["html decoder online", "html entity decoder", "decode html entities", "html decode", "how to decode html entities free", "best free html decoder", "html entity to text", "unescape html"] },
  { slug: "markdown-previewer", name: "Markdown Previewer", description: "Render Markdown to a live HTML preview with split-pane editing and real-time updates.", category: "Text Tools", categorySlug: "text", icon: "Eye", keywords: ["markdown preview online", "markdown viewer", "markdown editor free", "markdown previewer", "how to preview markdown online free", "best free markdown viewer", "live markdown preview", "markdown to html"] },

  // Developer Tools (15)
  { slug: "json-formatter", name: "JSON Formatter", description: "Prettify minified JSON with syntax highlighting, error detection, and tree view.", category: "Developer Tools", categorySlug: "dev", icon: "Braces", keywords: ["json formatter online", "prettify json", "json beautifier", "formater json", "json pretty print", "how to format json online free", "best free json formatter", "json viewer with syntax highlighting", "beautify json code"], popular: true },
  { slug: "json-validator", name: "JSON Validator", description: "Check JSON syntax and pinpoint exact error locations with line numbers and suggestions.", category: "Developer Tools", categorySlug: "dev", icon: "CheckCircle", keywords: ["json validator online", "check json syntax", "json error finder", "validater json", "validate json online", "how to check json syntax free", "best free json validator", "json linter", "json syntax checker"] },
  { slug: "json-to-csv", name: "JSON to CSV", description: "Flatten nested JSON arrays into downloadable CSV spreadsheets instantly.", category: "Developer Tools", categorySlug: "dev", icon: "Table", keywords: ["json to csv converter", "json to csv online", "export json to csv", "json to spreadsheet", "how to convert json to csv free", "best free json to csv tool", "json array to csv", "json to excel"] },
  { slug: "csv-to-json", name: "CSV to JSON", description: "Parse CSV data into structured JSON arrays with proper type inference and formatting.", category: "Developer Tools", categorySlug: "dev", icon: "ArrowsClockwise", keywords: ["csv to json converter", "csv to json online", "parse csv to json", "csv to array", "how to convert csv to json free", "best free csv to json tool", "spreadsheet to json", "csv parser online"] },
  { slug: "xml-formatter", name: "XML Formatter", description: "Pretty-print minified XML with correct indentation and syntax coloring.", category: "Developer Tools", categorySlug: "dev", icon: "FileCode", keywords: ["xml formatter online", "prettify xml", "xml beautifier", "formater xml", "xml pretty print", "how to format xml online free", "best free xml formatter", "xml viewer", "beautify xml code"] },
  { slug: "base64-encode", name: "Base64 Encoder & Decoder", description: "Encode text or files to Base64 and decode Base64 strings back to plain text.", category: "Developer Tools", categorySlug: "dev", icon: "Lock", keywords: ["base64 encoder online", "base64 decode", "base64 converter", "encodr base64", "encode text to base64", "how to encode base64 online free", "best free base64 encoder", "base64 encoder decoder", "base64 string encoder"], popular: true },
  { slug: "base64-decode", name: "Base64 Decoder", description: "Paste a Base64 string and instantly get the original text or binary data.", category: "Developer Tools", categorySlug: "dev", icon: "Unlock", keywords: ["base64 decoder online", "decode base64", "base64 to text", "decodr base64", "how to decode base64 online free", "best free base64 decoder", "base64 to string", "base64 decode text"] },
  { slug: "url-encode", name: "URL Encoder", description: "Encode special characters in URLs to make them safe for web transmission.", category: "Developer Tools", categorySlug: "dev", icon: "Link", keywords: ["url encoder online", "encode url", "percent encoding", "url encode", "how to encode url online free", "best free url encoder", "url string encoder", "special character encoder url"] },
  { slug: "url-decode", name: "URL Decoder", description: "Decode percent-encoded URL strings back to their original readable form.", category: "Developer Tools", categorySlug: "dev", icon: "RotateCcw", keywords: ["url decoder online", "decode url", "percent decoding", "url decode", "how to decode url online free", "best free url decoder", "url string decoder", "unescape url"] },
  { slug: "regex-tester", name: "Regex Tester", description: "Test regular expressions with live match highlighting and capture group display.", category: "Developer Tools", categorySlug: "dev", icon: "Terminal", keywords: ["regex tester online", "regular expression tester", "regex previewer", "regex test tool", "how to test regex online free", "best free regex tester", "regex pattern matcher", "regex validator online"], popular: true },
  { slug: "uuid-generator", name: "UUID Generator", description: "Generate UUID v4 identifiers one at a time or in batches up to 1000.", category: "Developer Tools", categorySlug: "dev", icon: "Fingerprint", keywords: ["uuid generator online", "random uuid", "uuid v4 generator", "uuid genrator", "generate uuid free", "how to generate uuid online", "best free uuid generator", "unique id generator", "guid generator"] },
  { slug: "hash-generator", name: "Hash Generator", description: "Compute MD5, SHA1, SHA256, and SHA512 hashes from any input text securely.", category: "Developer Tools", categorySlug: "dev", icon: "Key", keywords: ["hash generator online", "md5 hash", "sha256 generator", "hash generater", "generate hash free", "how to generate hash online", "best free hash generator", "sha1 hash generator", "hash calculator"] },
  { slug: "jwt-decoder", name: "JWT Decoder", description: "Decode JSON Web Tokens to view the header, payload, and signature clearly.", category: "Developer Tools", categorySlug: "dev", icon: "Ticket", keywords: ["jwt decoder online", "json web token decoder", "jwt viewer", "jwt decode free", "how to decode jwt online", "best free jwt decoder", "jwt token viewer", "jwt payload decoder"] },
  { slug: "sql-formatter", name: "SQL Formatter", description: "Beautify and indent messy SQL queries with keyword-aware formatting and highlighting.", category: "Developer Tools", categorySlug: "dev", icon: "Database", keywords: ["sql formatter online", "sql beautifier", "format sql query", "sql formater", "prettify sql", "how to format sql online free", "best free sql formatter", "sql query beautifier", "sql code formatter"] },
  { slug: "css-minifier", name: "CSS Minifier", description: "Strip whitespace and comments from CSS to produce compact production-ready code.", category: "Developer Tools", categorySlug: "dev", icon: "Minimize", keywords: ["css minifier online", "minify css", "compress css code", "css minify", "how to minify css online free", "best free css minifier", "css compressor", "minify css code"] },

  // Design Tools (10)
  { slug: "css-gradient-generator", name: "CSS Gradient Generator", description: "Build linear, radial, and conic CSS gradients with a live visual editor and code export.", category: "Web Design Tools", categorySlug: "design", icon: "Rainbow", keywords: ["css gradient generator", "gradient maker", "linear gradient tool", "css gradient maker", "how to create css gradient online free", "best free css gradient tool", "background gradient generator", "gradient css code"], popular: true },
  { slug: "box-shadow-generator", name: "Box Shadow Generator", description: "Design CSS box shadows with interactive controls for blur, spread, and color.", category: "Web Design Tools", categorySlug: "design", icon: "SquaresFour", keywords: ["box shadow generator", "css shadow maker", "drop shadow tool", "css box shadow", "how to create box shadow online free", "best free box shadow tool", "css shadow generator", "element shadow maker"] },
  { slug: "border-radius-generator", name: "Border Radius Generator", description: "Create complex CSS border-radius values with a visual corner editor and live preview.", category: "Web Design Tools", categorySlug: "design", icon: "Eyedropper", keywords: ["border radius generator", "css border radius", "rounded corners tool", "css border radius generator", "how to create border radius online free", "best free border radius tool", "rounded corners css", "border radius visual editor"] },
  { slug: "clip-path-generator", name: "CSS Clip Path Generator", description: "Shape element clipping paths using circles, polygons, and custom points visually.", category: "Web Design Tools", categorySlug: "design", icon: "Scissors", keywords: ["clip path generator", "css clip path", "shape clip tool", "css clip path generator", "how to create clip path online free", "best free clip path tool", "polygon clip path", "element shape clip"] },
  { slug: "color-palette-generator", name: "Color Palette Generator", description: "Generate harmonious color schemes from a base color using color theory rules.", category: "Web Design Tools", categorySlug: "design", icon: "Palette", keywords: ["color palette generator", "color scheme tool", "color harmony", "color palette creator", "how to generate color palette online free", "best free color palette tool", "color combination generator", "complementary color finder"], popular: true },
  { slug: "hex-rgb-converter", name: "HEX to RGB Converter", description: "Convert between HEX, RGB, HSL, and CSS color formats with one click.", category: "Web Design Tools", categorySlug: "design", icon: "Droplets", keywords: ["hex to rgb converter", "color code converter", "rgb to hex online", "hex to hsl", "how to convert hex to rgb online free", "best free color converter", "rgb to hsl converter", "color code tool"] },
  { slug: "tailwind-color-generator", name: "Tailwind Color Generator", description: "Find the closest Tailwind CSS class for any custom HEX or RGB color value.", category: "Web Design Tools", categorySlug: "design", icon: "Paintbrush", keywords: ["tailwind color generator", "tailwind color picker", "tailwind color classes", "tailwind color palette", "how to find tailwind colors online free", "best free tailwind color tool", "tailwind hex to class", "tailwind color converter"] },
  { slug: "font-pairing-tool", name: "Font Pairing Tool", description: "Discover complementary Google Font combinations for headings and body text.", category: "Web Design Tools", categorySlug: "design", icon: "Type", keywords: ["font pairing tool", "font combination finder", "google fonts pairing", "font pair generator", "how to find font pairings online free", "best free font pairing tool", "typography pairing", "heading body font combo"] },
  { slug: "svg-wave-generator", name: "SVG Wave Generator", description: "Design smooth SVG wave dividers with customizable amplitude and segments.", category: "Web Design Tools", categorySlug: "design", icon: "Waves", keywords: ["svg wave generator", "wave shape creator", "svg divider tool", "svg wave divider", "how to create svg wave online free", "best free svg wave tool", "section divider svg", "wave border generator"] },
  { slug: "css-animation-generator", name: "CSS Animation Generator", description: "Craft CSS keyframe animations with a timeline editor and live preview.", category: "Web Design Tools", categorySlug: "design", icon: "Play", keywords: ["css animation generator", "keyframe animation tool", "css animation maker", "css animation creator", "how to create css animation online free", "best free css animation tool", "css keyframe generator", "transition animation maker"] },

  // Calculators (15)
  { slug: "bmi-calculator", name: "BMI Calculator", description: "Compute your Body Mass Index from height and weight with WHO category labels.", category: "Calculators", categorySlug: "calculators", icon: "Heart", keywords: ["bmi calculator online", "body mass index calculator", "bmi calculator free", "calulator bmi", "bmi caluclator", "how to calculate bmi free", "best free bmi calculator", "bmi formula calculator", "weight height bmi"], popular: true },
  { slug: "age-calculator", name: "Age Calculator", description: "Find your exact age in years, months, days, hours, and total days lived.", category: "Calculators", categorySlug: "calculators", icon: "Calendar", keywords: ["age calculator online", "calculate age", "age calculator free", "age calulator", "exact age calculator", "how to calculate age online free", "best free age calculator", "birthday calculator", "days alive calculator"], popular: true },
  { slug: "percentage-calculator", name: "Percentage Calculator", description: "Solve percentage problems including increase, decrease, and difference formulas.", category: "Calculators", categorySlug: "calculators", icon: "Percent", keywords: ["percentage calculator online", "calculate percentage", "percent calculator free", "percent calulator", "percentage caluclator", "how to calculate percentage free", "best free percentage calculator", "percent increase calculator", "percentage formula"], popular: true },
  { slug: "loan-emi-calculator", name: "Loan EMI Calculator", description: "Calculate monthly EMI payments with a full amortization schedule breakdown.", category: "Calculators", categorySlug: "calculators", icon: "Landmark", keywords: ["loan emi calculator", "emi calculator online", "home loan calculator", "emi calulator", "loan calulator", "how to calculate emi free", "best free emi calculator", "monthly payment calculator", "car loan emi calculator"], popular: true },
  { slug: "compound-interest-calculator", name: "Compound Interest Calculator", description: "Project investment growth with compounding frequency and time period options.", category: "Calculators", categorySlug: "calculators", icon: "TrendingUp", keywords: ["compound interest calculator", "interest calculator online", "investment growth calculator", "compound interest calulator", "how to calculate compound interest free", "best free compound interest calculator", "interest rate calculator", "savings growth calculator"] },
  { slug: "discount-calculator", name: "Discount Calculator", description: "Determine the final sale price and total savings after applying a discount percentage.", category: "Calculators", categorySlug: "calculators", icon: "Tag", keywords: ["discount calculator online", "calculate discount", "sale price calculator", "discount calulator", "how to calculate discount free", "best free discount calculator", "percent off calculator", "shopping discount calculator"] },
  { slug: "gst-vat-calculator", name: "GST/VAT Calculator", description: "Add GST or VAT to any amount or reverse-calculate tax from a total price.", category: "Calculators", categorySlug: "calculators", icon: "Receipt", keywords: ["gst calculator", "vat calculator", "tax calculator online", "gst calulator", "vat caluclator", "how to calculate gst free", "best free gst calculator", "tax percentage calculator", "inclusive tax calculator"] },
  { slug: "tip-calculator", name: "Tip Calculator", description: "Split restaurant bills and calculate tip amounts with per-person breakdowns.", category: "Calculators", categorySlug: "calculators", icon: "DollarSign", keywords: ["tip calculator online", "gratuity calculator", "tip split calculator", "tip calulator", "restaurant bill splitter", "how to calculate tip free", "best free tip calculator", "dinner bill calculator", "group tip calculator"] },
  { slug: "time-difference-calculator", name: "Time Difference Calculator", description: "Find the exact duration between two dates including days, hours, and minutes.", category: "Calculators", categorySlug: "calculators", icon: "Calendar", keywords: ["time difference calculator", "date difference calculator", "days between dates", "time calulator", "how to calculate time difference free", "best free time difference calculator", "duration calculator", "between two dates calculator"] },
  { slug: "date-calculator", name: "Date Calculator", description: "Add or subtract days, weeks, months, or years from any starting date easily.", category: "Calculators", categorySlug: "calculators", icon: "CalendarBlank", keywords: ["date calculator", "add days to date", "subtract days from date", "date calulator", "how to add days to date free", "best free date calculator", "future date calculator", "date difference tool"] },
  { slug: "unit-converter", name: "Unit Converter", description: "Convert units for length, weight, temperature, volume, and area instantly online.", category: "Calculators", categorySlug: "calculators", icon: "Scales", keywords: ["unit converter online", "measurement converter", "convert units free", "unit calulator", "how to convert units online free", "best free unit converter", "metric converter", "imperial converter"], popular: true },
  { slug: "currency-converter", name: "Currency Converter", description: "Convert between world currencies using up-to-date exchange rate data in real time.", category: "Calculators", categorySlug: "calculators", icon: "Money", keywords: ["currency converter online", "exchange rate calculator", "money converter", "currency calulator", "how to convert currency free", "best free currency converter", "forex converter", "usd to eur converter"] },
  { slug: "scientific-calculator", name: "Scientific Calculator", description: "Perform trigonometry, logarithms, exponents, and other advanced math operations.", category: "Calculators", categorySlug: "calculators", icon: "Calculator", keywords: ["scientific calculator online", "free scientific calculator", "trigonometry calculator", "scientific calulator", "how to use scientific calculator free", "best free scientific calculator online", "math calculator", "algebra calculator"] },
  { slug: "fuel-cost-calculator", name: "Fuel Cost Calculator", description: "Estimate total fuel expenses for a trip using distance, mileage, and fuel price.", category: "Calculators", categorySlug: "calculators", icon: "Receipt", keywords: ["fuel cost calculator", "gas cost calculator", "trip fuel cost", "fuel calulator", "how to calculate fuel cost free", "best free fuel cost calculator", "gas mileage calculator", "petrol cost calculator"] },
  { slug: "calorie-calculator", name: "Calorie Calculator", description: "Calculate daily calorie needs based on age, weight, height, and activity level.", category: "Calculators", categorySlug: "calculators", icon: "Thermometer", keywords: ["calorie calculator", "bmr calculator", "tdee calculator online", "calorie calulator", "how to calculate calories free", "best free calorie calculator", "daily calorie needs", "weight loss calorie calculator"] },

  // Security Tools (7)
  { slug: "password-generator", name: "Password Generator", description: "Create strong random passwords with customizable length and character rules for maximum security.", category: "Security Tools", categorySlug: "security", icon: "Password", keywords: ["password generator online", "random password generator", "strong password maker", "passwrd generator", "how to create strong password free", "best free password generator", "secure password creator", "password generator no signup"], popular: true },
  { slug: "password-strength-checker", name: "Password Strength Checker", description: "Analyze password security with crack-time estimates and improvement tips.", category: "Security Tools", categorySlug: "security", icon: "Shield", keywords: ["password strength checker", "password security test", "is my password strong", "passwrd strength", "how to check password strength free", "best free password checker", "password analyzer", "secure password test"] },
  { slug: "md5-generator", name: "MD5 Generator", description: "Generate MD5 hash digests from any text string for integrity verification and security.", category: "Security Tools", categorySlug: "security", icon: "Hash", keywords: ["md5 generator online", "md5 hash calculator", "md5 checksum", "md5 genrator", "how to generate md5 hash free", "best free md5 generator", "md5 hash generator", "md5 string hash"] },
  { slug: "sha256-generator", name: "SHA256 Generator", description: "Compute SHA-256 cryptographic hashes for secure data fingerprinting and verification.", category: "Security Tools", categorySlug: "security", icon: "Lock", keywords: ["sha256 generator online", "sha256 hash calculator", "sha256 checksum", "sha256 genrator", "how to generate sha256 hash free", "best free sha256 generator", "sha-256 hash tool", "secure hash generator"] },
  { slug: "qr-code-generator", name: "QR Code Generator", description: "Create QR codes for URLs, text, WiFi credentials, and contact details instantly.", category: "Security Tools", categorySlug: "security", icon: "QrCode", keywords: ["qr code generator online", "create qr code free", "qr code maker", "qrcode generator", "how to create qr code free", "best free qr code generator", "qr code creator tool", "wifi qr code generator"], popular: true },
  { slug: "qr-code-scanner", name: "QR Code Scanner", description: "Decode QR codes by uploading an image file or using your device camera instantly.", category: "Security Tools", categorySlug: "security", icon: "ScanText", keywords: ["qr code scanner online", "scan qr code", "read qr code", "qrcode scanner", "how to scan qr code online free", "best free qr code scanner", "qr code reader", "decode qr code"] },
  { slug: "random-token-generator", name: "Random Token Generator", description: "Produce cryptographically secure tokens in hex, base64, or alphanumeric formats.", category: "Security Tools", categorySlug: "security", icon: "Key", keywords: ["random token generator", "secure token generator", "api key generator", "random token genrator", "how to generate secure token free", "best free token generator", "random string generator", "crypto token generator"] },

  // Misc Tools (11)
  { slug: "barcode-generator", name: "Barcode Generator", description: "Create scannable barcodes in CODE128, EAN, UPC, and other popular formats instantly.", category: "Misc Tools", categorySlug: "misc", icon: "Barcode", keywords: ["barcode generator online", "create barcode free", "barcode maker", "barcod generator", "how to create barcode free", "best free barcode generator", "code128 generator", "ean barcode creator"] },
  { slug: "random-number-generator", name: "Random Number Generator", description: "Generate random integers or decimals within any minimum and maximum range.", category: "Misc Tools", categorySlug: "misc", icon: "Shuffle", keywords: ["random number generator online", "random number tool", "generate random numbers", "random num generator", "how to generate random numbers free", "best free random number generator", "random integer generator", "random decimal generator"], popular: true },
  { slug: "dice-roller", name: "Dice Roller", description: "Roll virtual D4, D6, D8, D10, D12, and D20 dice with animated visible results.", category: "Misc Tools", categorySlug: "misc", icon: "DiceFive", keywords: ["dice roller online", "virtual dice", "roll dice online", "dice roller free", "how to roll dice online", "best free virtual dice roller", "d20 roller", "rpg dice roller"], popular: true },
  { slug: "coin-flip", name: "Coin Flip", description: "Flip a virtual coin for fair heads-or-tails random decision making online.", category: "Misc Tools", categorySlug: "misc", icon: "Coin", keywords: ["coin flip online", "virtual coin flip", "heads or tails", "coin toss", "how to flip coin online free", "best free coin flipper", "random coin flip", "digital coin toss"] },
  { slug: "uuid-batch-generator", name: "UUID Batch Generator", description: "Generate up to 1000 unique UUID v4 values at once for bulk data and testing needs.", category: "Misc Tools", categorySlug: "misc", icon: "Barcode", keywords: ["uuid batch generator", "generate multiple uuids", "bulk uuid generator", "uuid batch genrator", "how to generate multiple uuids free", "best free batch uuid generator", "mass uuid creator", "uuid list generator"] },
  { slug: "time-zone-converter", name: "Time Zone Converter", description: "Convert a date and time between any two of the world's time zones instantly.", category: "Misc Tools", categorySlug: "misc", icon: "Globe", keywords: ["time zone converter", "timezone converter online", "world clock converter", "time zone converter free", "how to convert time zones online", "best free timezone converter", "world time converter", "utc converter"] },
  { slug: "file-checksum-calculator", name: "File Checksum Calculator", description: "Compute MD5, SHA-256, and SHA-512 checksums for any uploaded file to verify integrity.", category: "Misc Tools", categorySlug: "misc", icon: "Fingerprint", keywords: ["file checksum calculator", "file hash calculator", "md5 file checksum", "file checksum free", "how to calculate file checksum online", "best free file checksum tool", "sha256 file hash", "file integrity checker"] },
  { slug: "internet-speed-test", name: "Internet Speed Test", description: "Measure your download and upload connection speed with a lightweight client-side test.", category: "Misc Tools", categorySlug: "misc", icon: "Lightning", keywords: ["internet speed test", "speed test online", "download speed test", "wifi speed test", "how to test internet speed free", "best free speed test", "bandwidth test", "connection speed checker"] },
  { slug: "spinner-wheel", name: "Spinner Wheel", description: "Spin the wheel with custom options for random picking, giveaways, and decisions.", category: "Misc Tools", categorySlug: "misc", icon: "ArrowsClockwise", keywords: ["spin the wheel", "random picker wheel", "wheel spinner online", "decision maker", "spinner wheel free", "how to spin wheel online", "best free spinner wheel", "random name picker wheel", "giveaway wheel"], popular: true },
  { slug: "file-converter", name: "File Converter", description: "Convert files between formats instantly. Supports images, text, and more. 100% client-side, no upload needed.", category: "Misc Tools", categorySlug: "misc", icon: "ArrowsClockwise", keywords: ["file converter online", "convert file format", "image converter", "text converter", "png to jpg", "csv to json", "file converter free", "convreter file", "how to convert file format free", "best free file converter tool", "document converter"], popular: true },
  { slug: "resume-builder", name: "Resume Builder", description: "Create a professional resume in minutes with multiple templates and instant PDF export.", category: "Misc Tools", categorySlug: "misc", icon: "FileText", keywords: ["resume builder", "cv maker", "create resume online", "resume builder free", "resum builder", "how to make resume online free", "best free resume builder", "cv creator tool", "professional resume maker"], popular: true },

  // Social Media Tools (4)
  { slug: "instagram-bio-counter", name: "Instagram Bio Counter", description: "Count characters, words, and lines for Instagram bios and captions with live character limits.", category: "Social Media Tools", categorySlug: "social-media", icon: "TextAa", keywords: ["instagram bio character counter", "instagram caption counter", "instagram text limit", "insta bio counter", "how to count instagram bio characters free", "best free instagram character counter", "instagram bio length checker", "ig caption counter"], popular: true },
  { slug: "username-validator", name: "Username Validator", description: "Check if usernames meet Instagram, TikTok, and Twitter/X format requirements instantly.", category: "Social Media Tools", categorySlug: "social-media", icon: "CheckCircle", keywords: ["instagram username validator", "username format checker", "social media username rules", "username validater", "how to check username availability free", "best free username validator", "tiktok username checker", "twitter username rules"] },
  { slug: "social-image-resizer", name: "Social Media Image Resizer", description: "Resize images for Instagram, Facebook, Twitter, LinkedIn, and YouTube with preset sizes.", category: "Social Media Tools", categorySlug: "social-media", icon: "Image", keywords: ["social media image resizer", "instagram image resizer", "resize image for social media", "social image resizer", "how to resize image for instagram free", "best free social media resizer", "facebook cover resizer", "youtube thumbnail resizer"], popular: true },
  { slug: "hashtag-counter", name: "Hashtag Counter", description: "Count hashtags in your text and get platform-specific limits for Instagram and TikTok.", category: "Social Media Tools", categorySlug: "social-media", icon: "Hash", keywords: ["hashtag counter", "instagram hashtag counter", "hashtag generator", "hashtag countr", "how to count hashtags online free", "best free hashtag counter", "tiktok hashtag counter", "social media hashtag tool"] },

  // AI Writing Tools (12)
  { slug: "essay-writer", name: "AI Essay Writer", description: "Generate well-structured essays on any topic with AI-powered writing assistance and research support.", category: "AI Writing Tools", categorySlug: "ai-writing", icon: "Pen", keywords: ["ai essay writer", "essay generator", "write essay online", "ai writing tool", "essy writer", "how to write essay with ai free", "best ai essay writer", "ai writing assistant", "essay maker online"], popular: true },
  { slug: "paragraph-writer", name: "AI Paragraph Writer", description: "Generate coherent paragraphs on any subject with AI writing assistance and topic control.", category: "AI Writing Tools", categorySlug: "ai-writing", icon: "AlignLeft", keywords: ["ai paragraph writer", "paragraph generator", "write paragraph online", "ai paragraph genrator", "how to write paragraph with ai free", "best ai paragraph writer", "ai text generator", "content paragraph maker"] },
  { slug: "story-generator", name: "AI Story Generator", description: "Create engaging short stories and narratives with AI-powered creativity and genre options.", category: "AI Writing Tools", categorySlug: "ai-writing", icon: "BookOpen", keywords: ["ai story generator", "short story creator", "story writer online", "ai story writer", "how to create story with ai free", "best ai story generator", "fiction writer ai", "narrative generator"] },
  { slug: "blog-generator", name: "AI Blog Generator", description: "Generate complete blog posts on any topic with proper structure and SEO-friendly content.", category: "AI Writing Tools", categorySlug: "ai-writing", icon: "Article", keywords: ["ai blog generator", "blog post writer", "blog content creator", "ai blog writer", "how to write blog post with ai free", "best ai blog generator", "seo blog writer", "article generator ai"], popular: true },
  { slug: "blog-outline", name: "AI Blog Outline", description: "Generate structured blog outlines with headings, subheadings, and key points for any topic.", category: "AI Writing Tools", categorySlug: "ai-writing", icon: "ListDashes", keywords: ["blog outline generator", "ai outline tool", "blog structure creator", "blog outline ai", "how to create blog outline with ai free", "best ai outline generator", "content outline tool", "article outline maker"] },
  { slug: "faq-generator", name: "AI FAQ Generator", description: "Automatically generate relevant FAQ sections from any content or topic with AI.", category: "AI Writing Tools", categorySlug: "ai-writing", icon: "Question", keywords: ["faq generator", "ai faq creator", "generate faq online", "faq genrator", "how to create faq with ai free", "best ai faq generator", "frequently asked questions maker", "faq content generator"] },
  { slug: "grammar-fixer", name: "AI Grammar Fixer", description: "Fix grammar, spelling, and punctuation errors in your text instantly with AI.", category: "AI Writing Tools", categorySlug: "ai-writing", icon: "CheckCircle", keywords: ["grammar checker", "fix grammar online", "ai grammar tool", "grammer checker", "how to fix grammar online free", "best ai grammar fixer", "spelling corrector", "punctuation checker"], popular: true },
  { slug: "sentence-rewriter", name: "AI Sentence Rewriter", description: "Rewrite sentences to improve clarity, tone, or style while preserving the original meaning.", category: "AI Writing Tools", categorySlug: "ai-writing", icon: "ArrowsClockwise", keywords: ["sentence rewriter", "paraphrase tool", "rewrite text online", "ai paraphraser", "paraphase tool", "how to rewrite sentence with ai free", "best ai sentence rewriter", "text paraphraser ai", "content rephraser"] },
  { slug: "content-improver", name: "AI Content Improver", description: "Enhance and polish your writing for better readability, engagement, and professionalism.", category: "AI Writing Tools", categorySlug: "ai-writing", icon: "Sparkle", keywords: ["content improver", "ai text enhancer", "improve writing online", "ai content improver", "how to improve writing with ai free", "best ai content improver", "text polisher", "writing enhancer ai"] },
  { slug: "business-name-generator", name: "AI Business Name Generator", description: "Generate creative and memorable business name ideas for your startup or brand.", category: "AI Writing Tools", categorySlug: "ai-writing", icon: "Lightbulb", keywords: ["business name generator", "startup name ideas", "ai business naming", "business name genrator", "how to generate business name with ai free", "best ai business name generator", "company name creator", "brand name ideas ai"], popular: true },
  { slug: "linkedin-post-generator", name: "AI LinkedIn Post Generator", description: "Create professional LinkedIn posts that drive engagement and grow your network.", category: "AI Writing Tools", categorySlug: "ai-writing", icon: "ShareNetwork", keywords: ["linkedin post generator", "linkedin content creator", "ai linkedin writer", "linkedin post genrator", "how to write linkedin post with ai free", "best ai linkedin post generator", "professional post creator", "linkedin content ai"] },
  { slug: "instagram-caption-generator", name: "AI Instagram Caption Generator", description: "Generate creative Instagram captions with hashtags and emoji suggestions for more engagement.", category: "AI Writing Tools", categorySlug: "ai-writing", icon: "Camera", keywords: ["instagram caption generator", "ig caption writer", "social media caption creator", "instagram caption genrator", "how to write instagram caption with ai free", "best ai instagram caption generator", "ig caption ai", "social post caption maker"] },
];

export function getToolsByCategory(categorySlug: string): Tool[] {
  return tools.filter(t => t.categorySlug === categorySlug);
}

export function getTool(categorySlug: string, toolSlug: string): Tool | undefined {
  return tools.find(t => t.categorySlug === categorySlug && t.slug === toolSlug);
}

export function getRelatedTools(tool: Tool, count = 4): Tool[] {
  return tools
    .filter(t => t.categorySlug === tool.categorySlug && t.slug !== tool.slug)
    .slice(0, count);
}

export function getPopularTools(count = 8): Tool[] {
  return tools.filter(t => t.popular).slice(0, count);
}

export function searchTools(query: string): Tool[] {
  if (!query.trim()) return [];

  const q = query.toLowerCase().trim();

  const scored = tools.map(tool => {
    let maxScore = 0;

    const nameScore = fuzzyScore(q, tool.name.toLowerCase());
    maxScore = Math.max(maxScore, nameScore * 1.0);

    const slugWords = tool.slug.replace(/-/g, ' ');
    const slugScore = fuzzyScore(q, slugWords);
    maxScore = Math.max(maxScore, slugScore * 0.9);

    const descScore = fuzzyScore(q, tool.description.toLowerCase());
    maxScore = Math.max(maxScore, descScore * 0.7);

    for (const kw of tool.keywords) {
      const kwScore = fuzzyScore(q, kw.toLowerCase());
      maxScore = Math.max(maxScore, kwScore * 1.0);
    }

    const catScore = fuzzyScore(q, tool.category.toLowerCase());
    maxScore = Math.max(maxScore, catScore * 0.5);

    return { tool, score: maxScore };
  });

  return scored
    .filter(s => s.score >= 0.45)
    .sort((a, b) => b.score - a.score)
    .map(s => s.tool);
}

export function getToolColor(slug: string, defaultColor: string): string {
  const s = slug.toLowerCase();
  if (
    s.includes("protect") ||
    s.includes("unlock") ||
    s.includes("sign") ||
    s.includes("watermark") ||
    s.includes("password") ||
    s.includes("hash") ||
    s.includes("md5") ||
    s.includes("sha") ||
    s.includes("validator") ||
    s.includes("checker")
  ) {
    return "#EC4899"; // Pink for Security/Verification tools
  }
  if (
    s.includes("to") ||
    s.includes("extract") ||
    s.includes("ocr") ||
    s.includes("converter") ||
    s.includes("encoder") ||
    s.includes("decoder") ||
    s.includes("picker")
  ) {
    return "#3B82F6"; // Blue for Conversion/Extraction tools
  }
  return defaultColor; // Fallback to current category color
}
