import fs from "fs/promises";
import path from "path";
import { existsSync } from "fs";
import { categories, tools } from "../src/lib/tools.ts";
import { blogPosts } from "../src/app/blog/page.tsx";

const BASE_URL = "https://www.krynntools.online";
const DIST_DIR = path.resolve(import.meta.dirname, "../dist/public");
const INDEX_HTML_PATH = path.join(DIST_DIR, "index.html");

async function prerender() {
  try {
    // 1. Read index.html shell generated by Vite
    const indexHtml = await fs.readFile(INDEX_HTML_PATH, "utf-8");

    const urls: { path: string; title: string; desc: string; schema?: object }[] = [];

    // --- Homepage (prerender is just index.html itself, but we can also ensure it has correct canonical) ---
    urls.push({
      path: "",
      title: "Krynn Tools — 140+ Free Online Tools | PDF, Image, AI, Converter",
      desc: "140+ free online tools — Compress PDF, Remove Background, Image Upscaler, Resume Builder, QR Code Generator, AI Writing Tools, and more. No signup required. Runs in your browser."
    });

    // --- Static Pages ---
    const staticPages = [
      {
        slug: "about",
        title: "About Us | Krynn Tools",
        desc: "Learn more about Krynn Tools, our values, and our privacy-first local browser execution model."
      },
      {
        slug: "contact",
        title: "Contact Us | Krynn Tools",
        desc: "Get in touch with the Krynn Tools support team for suggestions, bug reports, or partnerships."
      },
      {
        slug: "blog",
        title: "Blog & Tutorials | Krynn Tools",
        desc: "Tips, guides, and tutorials for getting the most out of free online tools. Read our detailed write-ups."
      },
      {
        slug: "privacy-policy",
        title: "Privacy Policy | Krynn Tools",
        desc: "Our privacy policy explaining how we guarantee your file security by running everything locally inside your browser."
      },
      {
        slug: "terms-of-service",
        title: "Terms of Service | Krynn Tools",
        desc: "Read the terms of service agreement for using Krynn Tools online utility tools."
      },
      {
        slug: "cookie-policy",
        title: "Cookie Policy | Krynn Tools",
        desc: "Understand how we use cookies and caching to speed up your local browser utility executions."
      },
      {
        slug: "disclaimer",
        title: "Disclaimer | Krynn Tools",
        desc: "Disclaimer terms regarding calculations, conversions, and output files from Krynn Tools."
      }
    ];

    staticPages.forEach((p) => {
      urls.push({
        path: p.slug,
        title: p.title,
        desc: p.desc
      });
    });

    // --- Category Pages ---
    categories.forEach((cat) => {
      urls.push({
        path: cat.slug,
        title: `${cat.name} Online Free — No Signup Required | Krynn Tools`,
        desc: `Free online ${cat.name.toLowerCase()} — ${cat.description} 100% free, no signup, no watermark. All tools run in your browser for instant & private results.`
      });
    });

    // --- Tool Pages ---
    tools.forEach((tool) => {
      const toolTitle = `${tool.name} Online Free — No Signup | Krynn Tools`;
      const toolDesc = `${tool.description} Free, fast, and private — runs entirely in your browser. No signup, no watermark, no file size limits. Try it now!`;
      
      const schema = {
        "@context": "https://schema.org",
        "@type": "SoftwareApplication",
        "name": tool.name,
        "operatingSystem": "All",
        "applicationCategory": "UtilityApplication",
        "offers": {
          "@type": "Offer",
          "price": "0",
          "priceCurrency": "USD"
        },
        "description": tool.description
      };

      urls.push({
        path: `${tool.categorySlug}/${tool.slug}`,
        title: toolTitle,
        desc: toolDesc,
        schema
      });
    });

    // --- Blog Pages ---
    blogPosts.forEach((post) => {
      const schema = {
        "@context": "https://schema.org",
        "@type": "Article",
        "headline": post.title,
        "description": post.description,
        "datePublished": post.date,
        "author": {
          "@type": "Organization",
          "name": "Krynn Tools"
        },
        "publisher": {
          "@type": "Organization",
          "name": "Krynn Tools"
        }
      };

      urls.push({
        path: `blog/${post.slug}`,
        title: post.title,
        desc: post.description,
        schema
      });
    });

    // --- Trending News Pages ---
    try {
      const newsDataPath = path.resolve(import.meta.dirname, "../public/trending-news/data.json");
      if (existsSync(newsDataPath)) {
        const newsRaw = await fs.readFile(newsDataPath, "utf-8");
        const newsData = JSON.parse(newsRaw);
        if (newsData && Array.isArray(newsData.articles)) {
          // Pre-render the main trending-news list page
          urls.push({
            path: "trending-news",
            title: "Trending Tech News — AI, Technology & Cybersecurity | Krynn Tools",
            desc: "Stay ahead with the latest in technology, AI, and cybersecurity. Curated from TechCrunch, The Verge, WIRED, and more — updated automatically."
          });

          // Pre-render individual news articles
          newsData.articles.forEach((article: any) => {
            const schema = {
              "@context": "https://schema.org",
              "@type": "NewsArticle",
              "headline": article.title,
              "description": article.summary,
              "image": article.image || undefined,
              "datePublished": article.publishedAt,
              "dateModified": article.publishedAt,
              "author": {
                "@type": "Organization",
                "name": article.source
              },
              "publisher": {
                "@type": "Organization",
                "name": "Krynn Tools",
                "url": BASE_URL,
                "logo": {
                  "@type": "ImageObject",
                  "url": `${BASE_URL}/logo.png`
                }
              },
              "mainEntityOfPage": {
                "@type": "WebPage",
                "@id": `${BASE_URL}/trending-news/${article.slug}`
              }
            };

            urls.push({
              path: `trending-news/${article.slug}`,
              title: `${article.title} | Krynn Tools`,
              desc: article.summary,
              schema
            });
          });
        }
      }
    } catch (e) {
      console.error("Failed to prerender trending news:", e);
    }

    // Prerender loop
    for (const item of urls) {
      const fullUrl = item.path ? `${BASE_URL}/${item.path}` : `${BASE_URL}/`;
      
      let html = indexHtml;

      // Replace metadata
      html = html.replace(/<title>.*?<\/title>/g, `<title>${item.title}</title>`);
      html = html.replace(/<meta name="description" content=".*?" \/>/g, `<meta name="description" content="${item.desc}" />`);
      html = html.replace(/<meta property="og:title" content=".*?" \/>/g, `<meta property="og:title" content="${item.title}" />`);
      html = html.replace(/<meta property="og:description" content=".*?" \/>/g, `<meta property="og:description" content="${item.desc}" />`);
      html = html.replace(/<meta property="og:url" content=".*?" \/>/g, `<meta property="og:url" content="${fullUrl}" />`);
      html = html.replace(/<meta name="twitter:title" content=".*?" \/>/g, `<meta name="twitter:title" content="${item.title}" />`);
      html = html.replace(/<meta name="twitter:description" content=".*?" \/>/g, `<meta name="twitter:description" content="${item.desc}" />`);
      html = html.replace(/<link rel="canonical" href=".*?" \/>/g, `<link rel="canonical" href="${fullUrl}" />`);
      html = html.replace(/<link rel="alternate" hreflang="en" href=".*?" \/>/g, `<link rel="alternate" hreflang="en" href="${fullUrl}" />`);
      html = html.replace(/<link rel="alternate" hreflang="x-default" href=".*?" \/>/g, `<link rel="alternate" hreflang="x-default" href="${fullUrl}" />`);

      // Inject extra schemas if present
      if (item.schema) {
        const schemaString = `\n    <script type="application/ld+json">\n    ${JSON.stringify(item.schema, null, 2).replace(/\n/g, "\n    ")}\n    </script>`;
        html = html.replace("</head>", `${schemaString}\n  </head>`);
      }

      // Write output
      if (item.path === "") {
        // Just overwrite index.html with the correct canonicals/title (in case Vite generated defaults)
        await fs.writeFile(INDEX_HTML_PATH, html, "utf-8");
      } else {
        const outDir = path.join(DIST_DIR, item.path);
        await fs.mkdir(outDir, { recursive: true });
        await fs.writeFile(path.join(outDir, "index.html"), html, "utf-8");
      }
    }

    console.log(`Successfully pre-rendered ${urls.length} pages in dist/public/ for SEO!`);
  } catch (err) {
    console.error("Prerendering failed:", err);
  }
}

prerender().catch(console.error);
