import fs from "fs/promises";
import path from "path";
import { existsSync } from "fs";
import { categories, tools } from "../src/lib/tools.ts";
import { blogPosts } from "../src/lib/blog-data.ts";

const BASE_URL = "https://www.krynntools.online";
const DIST_DIR = path.resolve(import.meta.dirname, "../dist/public");
const INDEX_HTML_PATH = path.join(DIST_DIR, "index.html");

/** Escape special HTML characters so they are safe inside attribute values. */
function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/"/g, "&quot;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

async function prerender() {
  try {
    // 1. Read index.html shell generated by Vite
    const indexHtml = await fs.readFile(INDEX_HTML_PATH, "utf-8");

    const urls: { path: string; title: string; desc: string; keywords: string; schema?: object }[] = [];

    const defaultKeywords = "free online tools, PDF tools, image compressor, remove background, QR code generator, resume builder, AI writing tools, grammar checker, word counter, JSON formatter, base64 encoder, password generator, BMI calculator, unit converter, file converter, image upscaler, OCR, text to speech, plagiarism checker";

    // --- Homepage (prerender is just index.html itself, but we can also ensure it has correct canonical) ---
    urls.push({
      path: "",
      title: "Krynn Tools — 140+ Free Online Tools | PDF, Image, AI, Converter",
      desc: "140+ free online tools — Compress PDF, Remove Background, Image Upscaler, Resume Builder, QR Code Generator, AI Writing Tools, and more. No signup required. Runs in your browser.",
      keywords: defaultKeywords
    });

    // --- Static Pages ---
    const staticPages = [
      {
        slug: "about",
        title: "About Us | Krynn Tools",
        desc: "Learn more about Krynn Tools, our values, and our privacy-first local browser execution model."
      },
      {
        slug: "contact",
        title: "Contact Us | Krynn Tools",
        desc: "Get in touch with the Krynn Tools support team for suggestions, bug reports, or partnerships."
      },
      {
        slug: "blog",
        title: "Blog & Tutorials | Krynn Tools",
        desc: "Tips, guides, and tutorials for getting the most out of free online tools. Read our detailed write-ups."
      },
      {
        slug: "privacy-policy",
        title: "Privacy Policy | Krynn Tools",
        desc: "Our privacy policy explaining how we guarantee your file security by running everything locally inside your browser."
      },
      {
        slug: "terms-of-service",
        title: "Terms of Service | Krynn Tools",
        desc: "Read the terms of service agreement for using Krynn Tools online utility tools."
      },
      {
        slug: "cookie-policy",
        title: "Cookie Policy | Krynn Tools",
        desc: "Understand how we use cookies and caching to speed up your local browser utility executions."
      },
      {
        slug: "disclaimer",
        title: "Disclaimer | Krynn Tools",
        desc: "Disclaimer terms regarding calculations, conversions, and output files from Krynn Tools."
      }
    ];

    staticPages.forEach((p) => {
      urls.push({
        path: p.slug,
        title: p.title,
        desc: p.desc,
        keywords: `${p.title.toLowerCase().replace(" | krynn tools", "")}, free online tools, krynn tools`
      });
    });

    // --- Comparison / Alternative Landing Pages ---
    const comparisonPages = [
      {
        slug: "ilovepdf-alternative",
        title: "Best Free iLovePDF Alternative 2026 — No Upload, No Limits | Krynn Tools",
        desc: "Krynn Tools is the best free iLovePDF alternative. 20+ PDF tools with no file uploads, no sign-up, no rate limits, and 100% private browser-side processing.",
        keywords: "ilovepdf alternative, ilovepdf free alternative, free pdf tools online, ilovepdf no upload alternative, krynn tools"
      },
      {
        slug: "smallpdf-alternative",
        title: "Best Free Smallpdf Alternative 2026 — Unlimited, No Sign-up | Krynn Tools",
        desc: "Tired of Smallpdf's 2-task/day limit? Krynn Tools is a free Smallpdf alternative with unlimited PDF tools, no uploads, no sign-up, and complete privacy.",
        keywords: "smallpdf alternative, smallpdf free alternative, free pdf tools unlimited, smallpdf no limit alternative, krynn tools"
      },
    ];
    comparisonPages.forEach((p) => {
      const schema = {
        "@context": "https://schema.org",
        "@type": "WebPage",
        "name": p.title,
        "description": p.desc,
        "url": `${BASE_URL}/${p.slug}`,
        "breadcrumb": {
          "@type": "BreadcrumbList",
          "itemListElement": [
            { "@type": "ListItem", "position": 1, "name": "Home", "item": BASE_URL },
            { "@type": "ListItem", "position": 2, "name": p.title.split(" — ")[0], "item": `${BASE_URL}/${p.slug}` }
          ]
        }
      };
      urls.push({ path: p.slug, title: p.title, desc: p.desc, keywords: p.keywords, schema });
    });

    // --- Category Pages ---
    categories.forEach((cat) => {
      urls.push({
        path: cat.slug,
        title: `${cat.name} Online Free — No Signup Required | Krynn Tools`,
        desc: `Free online ${cat.name.toLowerCase()} — ${cat.description} 100% free, no signup, no watermark. All tools run in your browser for instant & private results.`,
        keywords: `${cat.name.toLowerCase()}, free online ${cat.name.toLowerCase()}, browser based ${cat.name.toLowerCase()}, krynn tools`
      });
    });

    // --- Tool Pages ---
    tools.forEach((tool) => {
      const toolTitle = tool.seoTitle || `${tool.name} Online Free — No Signup | Krynn Tools`;
      const toolDesc = tool.seoDescription || `${tool.description} Free, fast, and private — runs entirely in your browser. No signup, no watermark, no file size limits. Try it now!`;
      
      const schema = {
        "@context": "https://schema.org",
        "@type": "SoftwareApplication",
        "name": tool.name,
        "operatingSystem": "Web Browser",
        "applicationCategory": "UtilityApplication",
        "featureList": tool.keywords?.slice(0, 5).join(", ") || tool.description,
        "offers": {
          "@type": "Offer",
          "price": "0",
          "priceCurrency": "USD"
        },
        "aggregateRating": {
          "@type": "AggregateRating",
          "ratingValue": "4.8",
          "ratingCount": "127",
          "bestRating": "5",
          "worstRating": "1"
        },
        "description": tool.description,
        "url": `${BASE_URL}/${tool.categorySlug}/${tool.slug}`
      };

      urls.push({
        path: `${tool.categorySlug}/${tool.slug}`,
        title: toolTitle,
        desc: toolDesc,
        keywords: tool.keywords.slice(0, 15).join(", "),
        schema
      });
    });

    // --- Blog Pages ---
    blogPosts.forEach((post) => {
      const schema = {
        "@context": "https://schema.org",
        "@type": "Article",
        "headline": post.title,
        "description": post.description,
        "image": post.image?.startsWith("/")
          ? `${BASE_URL}${post.image}`
          : post.image || `${BASE_URL}/og-default.png`,
        "datePublished": post.date,
        "dateModified": post.date,
        "mainEntityOfPage": {
          "@type": "WebPage",
          "@id": `${BASE_URL}/blog/${post.slug}`
        },
        "author": {
          "@type": "Person",
          "name": "Krynn Tools Team"
        },
        "publisher": {
          "@type": "Organization",
          "name": "Krynn Tools",
          "logo": {
            "@type": "ImageObject",
            "url": `${BASE_URL}/logo.png`
          }
        }
      };

      const blogKeywords = `${post.title.toLowerCase().replace(/ - /g, ", ").replace(/ /g, ", ")}, krynn tools blog`;

      urls.push({
        path: `blog/${post.slug}`,
        title: post.title,
        desc: post.description,
        keywords: blogKeywords,
        schema
      });
    });

    // --- Trending News Pages ---
    try {
      const newsDataPath = path.resolve(import.meta.dirname, "../public/trending-news/data.json");
      if (existsSync(newsDataPath)) {
        const newsRaw = await fs.readFile(newsDataPath, "utf-8");
        const newsData = JSON.parse(newsRaw);
        if (newsData && Array.isArray(newsData.articles)) {
          // Pre-render the main trending-news list page
          urls.push({
            path: "trending-news",
            title: "Trending Tech News — AI, Technology & Cybersecurity | Krynn Tools",
            desc: "Stay ahead with the latest in technology, AI, and cybersecurity. Curated from TechCrunch, The Verge, WIRED, and more — updated automatically.",
            keywords: "trending tech news, ai news, technology news, cybersecurity news, tech article aggregator"
          });

          // Pre-render individual news articles
          newsData.articles.forEach((article: any) => {
            const schema = {
              "@context": "https://schema.org",
              "@type": "NewsArticle",
              "headline": article.title,
              "description": article.summary,
              "image": article.image || undefined,
              "datePublished": article.publishedAt,
              "dateModified": article.publishedAt,
              "author": {
                "@type": "Organization",
                "name": article.source
              },
              "publisher": {
                "@type": "Organization",
                "name": "Krynn Tools",
                "url": BASE_URL,
                "logo": {
                  "@type": "ImageObject",
                  "url": `${BASE_URL}/logo.png`
                }
              },
              "mainEntityOfPage": {
                "@type": "WebPage",
                "@id": `${BASE_URL}/trending-news/${article.slug}`
              }
            };

            const newsKeywords = article.tags ? [...article.tags, article.category].join(', ') : article.category;

            urls.push({
              path: `trending-news/${article.slug}`,
              title: `${article.title} | Krynn Tools`,
              desc: article.summary,
              keywords: newsKeywords,
              schema
            });
          });
        }
      }
    } catch (e) {
      console.error("Failed to prerender trending news:", e);
    }

    // Prerender loop
    for (const item of urls) {
      const fullUrl = item.path ? `${BASE_URL}/${item.path}` : `${BASE_URL}/`;
      
      let html = indexHtml;

      // Escape values before injecting into HTML attributes
      const safeTitle = escapeHtml(item.title);
      const safeDesc = escapeHtml(item.desc);
      const safeKeywords = escapeHtml(item.keywords);

      // Replace metadata
      html = html.replace(/<title>.*?<\/title>/g, `<title>${safeTitle}<\/title>`);
      html = html.replace(/<meta name="description" content=".*?" \/>/g, `<meta name="description" content="${safeDesc}" />`);
      html = html.replace(/<meta name="keywords" content=".*?" \/>/g, `<meta name="keywords" content="${safeKeywords}" />`);
      html = html.replace(/<meta property="og:title" content=".*?" \/>/g, `<meta property="og:title" content="${safeTitle}" />`);
      html = html.replace(/<meta property="og:description" content=".*?" \/>/g, `<meta property="og:description" content="${safeDesc}" />`);
      html = html.replace(/<meta property="og:url" content=".*?" \/>/g, `<meta property="og:url" content="${fullUrl}" />`);
      html = html.replace(/<meta name="twitter:title" content=".*?" \/>/g, `<meta name="twitter:title" content="${safeTitle}" />`);
      html = html.replace(/<meta name="twitter:description" content=".*?" \/>/g, `<meta name="twitter:description" content="${safeDesc}" />`);
      html = html.replace(/<link rel="canonical" href=".*?" \/>/g, `<link rel="canonical" href="${fullUrl}" />`);
      html = html.replace(/<link rel="alternate" hreflang="en" href=".*?" \/>/g, `<link rel="alternate" hreflang="en" href="${fullUrl}" />`);
      html = html.replace(/<link rel="alternate" hreflang="x-default" href=".*?" \/>/g, `<link rel="alternate" hreflang="x-default" href="${fullUrl}" />`);
      
      // Inject hreflang en-IN so Google knows this English content serves Indian users
      if (!html.includes('hreflang="en-IN"')) {
        html = html.replace(
          `<link rel="alternate" hreflang="en" href="${fullUrl}" />`,
          `<link rel="alternate" hreflang="en" href="${fullUrl}" />
    <link rel="alternate" hreflang="en-IN" href="${fullUrl}" />`
        );
      }

      // Inject extra schemas if present
      if (item.schema) {
        const schemaString = `\n    <script type="application/ld+json">\n    ${JSON.stringify(item.schema, null, 2).replace(/\n/g, "\n    ")}\n    </script>`;
        html = html.replace("</head>", `${schemaString}\n  </head>`);
      }

      // Write output
      if (item.path === "") {
        // Just overwrite index.html with the correct canonicals/title (in case Vite generated defaults)
        await fs.writeFile(INDEX_HTML_PATH, html, "utf-8");
      } else {
        const outDir = path.join(DIST_DIR, item.path);
        await fs.mkdir(outDir, { recursive: true });
        await fs.writeFile(path.join(outDir, "index.html"), html, "utf-8");
      }
    }

    console.log(`Successfully pre-rendered ${urls.length} pages in dist/public/ for SEO!`);
  } catch (err) {
    console.error("Prerendering failed:", err);
  }
}

prerender().catch(console.error);
