import { useState, useCallback, useEffect, useMemo } from "react";
import Breadcrumbs from "../layout/Breadcrumbs";
import StickyMobileCTA from "./StickyMobileCTA";
import AdSlot from "../AdSlot";
import { categories, tools } from "@/lib/tools";
import KrynnIcon from "../common/KrynnIcon";
import { CaretRight, Upload, CheckCircle, Shield, Lightning, DeviceMobile, Star } from "@phosphor-icons/react";

/* ── File Drop Zone ── */

interface FileDropZoneProps {
  accept?: string;
  onFile: (file: File) => void;
  label?: string;
}

export function FileDropZone({ accept = ".pdf,.jpg,.jpeg,.png,.webp", onFile, label }: FileDropZoneProps) {
  const [dragActive, setDragActive] = useState(false);

  const handleDrag = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    if (e.type === "dragenter" || e.type === "dragover") setDragActive(true);
    else if (e.type === "dragleave") setDragActive(false);
  }, []);

  const handleDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setDragActive(false);
    if (e.dataTransfer.files?.[0]) onFile(e.dataTransfer.files[0]);
  }, [onFile]);

  const handleChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files?.[0]) onFile(e.target.files[0]);
  }, [onFile]);

  return (
    <form
      onDragEnter={handleDrag}
      onDragLeave={handleDrag}
      onDragOver={handleDrag}
      onDrop={handleDrop}
      className={`drop-zone ${dragActive ? "active" : ""}`}
    >
      <input type="file" accept={accept} onChange={handleChange} className="hidden" id="file-upload" />
      <label htmlFor="file-upload" className="cursor-pointer">
        <div className="flex flex-col items-center gap-4">
          <div className="w-16 h-16 rounded-2xl bg-primary/10 flex items-center justify-center">
            <Upload size={28} weight="duotone" className="text-primary" />
          </div>
          <div>
            <p className="text-base font-semibold text-foreground">{label || "Drag & drop your file here"}</p>
            <p className="mt-1.5 text-sm text-muted-foreground">or click to browse files</p>
          </div>
          <p className="text-xs text-muted-foreground">
            Supports: {accept.replace(/\./g, "").toUpperCase().split(",").join(", ")}
          </p>
        </div>
      </label>
    </form>
  );
}

/* ── Trust Badges ── */

interface TrustBadge {
  icon: typeof Shield;
  label: string;
}

interface TrustStripProps {
  items?: TrustBadge[];
}

const DEFAULT_TRUST_ITEMS: TrustBadge[] = [
  { icon: Shield, label: "Files processed locally" },
  { icon: Lightning, label: "Instant processing" },
  { icon: CheckCircle, label: "100% free forever" },
  { icon: DeviceMobile, label: "Works on mobile" },
];

/** Use for AI-powered tools that call a remote API */
export const AI_TRUST_BADGES: TrustBadge[] = [
  { icon: CheckCircle, label: "No signup required" },
  { icon: Lightning, label: "Generated by AI" },
  { icon: Shield, label: "Not stored after use" },
  { icon: DeviceMobile, label: "Works on mobile" },
];

/** Use for network-dependent tools (e.g. speed test) */
export const NETWORK_TRUST_BADGES: TrustBadge[] = [
  { icon: CheckCircle, label: "No signup required" },
  { icon: Lightning, label: "Real-time measurement" },
  { icon: Shield, label: "100% free forever" },
  { icon: DeviceMobile, label: "Works on mobile" },
];


export function TrustStrip({ items }: TrustStripProps) {
  const badges = items ?? DEFAULT_TRUST_ITEMS;

  return (
    <div className="flex flex-wrap items-center justify-center gap-2 px-4">
      {badges.map(({ icon: Icon, label }) => (
        <span key={label} className="badge badge-muted flex items-center gap-1.5 px-3 py-1.5 text-xs">
          <Icon size={14} weight="fill" className="text-muted-foreground" />
          <span className="font-medium text-muted-foreground">{label}</span>
        </span>
      ))}
    </div>
  );
}

/* ── How To Use ── */

interface HowToUseProps { steps: string[]; }

export function HowToUse({ steps }: HowToUseProps) {
  return (
    <section className="rounded-2xl border border-border bg-card p-6 sm:p-8">
      <h2 className="text-lg font-bold mb-6 flex items-center gap-2">
        <div className="w-6 h-6 rounded-md bg-primary/10 flex items-center justify-center">
          <KrynnIcon name="ListNumbers" size={16} color="var(--color-primary)" weight="duotone" />
        </div>
        How to Use
      </h2>
      <ol className="space-y-4">
        {steps.map((step, i) => (
          <li key={i} className="flex gap-4">
            <span className="w-7 h-7 shrink-0 rounded-full bg-primary text-white text-sm font-bold flex items-center justify-center">{i + 1}</span>
            <span className="pt-0.5 text-sm text-muted-foreground leading-relaxed">{step}</span>
          </li>
        ))}
      </ol>
    </section>
  );
}

/* ── FAQ Accordion ── */

interface FAQItem { question: string; answer: string; }
interface FAQProps { items: FAQItem[]; }

export function FAQ({ items }: FAQProps) {
  return (
    <section className="rounded-2xl border border-border bg-card p-6 sm:p-8">
      <h2 className="text-lg font-bold mb-6 flex items-center gap-2">
        <div className="w-6 h-6 rounded-md bg-primary/10 flex items-center justify-center">
          <KrynnIcon name="Question" size={16} color="var(--color-primary)" weight="duotone" />
        </div>
        Frequently Asked Questions
      </h2>
      <div>
        {items.map((item, i) => (
          <details
            key={i}
            className="group"
          >
            <summary className="cursor-pointer min-h-[48px] py-4 flex items-center justify-between gap-4 font-semibold text-sm text-foreground group-open:text-primary outline-none list-none [&::-webkit-details-marker]:hidden">
              <span>{item.question}</span>
              <span className="transition-transform duration-200 group-open:rotate-180 shrink-0">
                <KrynnIcon name="CaretDown" size={16} weight="bold" />
              </span>
            </summary>
            <p className="pb-4 text-sm text-muted-foreground leading-relaxed">{item.answer}</p>
            {i < items.length - 1 && <div className="border-t border-border" />}
          </details>
        ))}
      </div>
    </section>
  );
}

/* ── Related Tools ── */

interface RelatedToolsProps {
  tools: Array<{ name: string; slug: string; categorySlug: string }>;
}

export function RelatedTools({ tools: relatedTools }: RelatedToolsProps) {
  return (
    <section className="rounded-2xl border border-border bg-card p-6 sm:p-8">
      <h2 className="text-lg font-bold mb-6 flex items-center gap-2">
        <div className="w-6 h-6 rounded-md bg-primary/10 flex items-center justify-center">
          <KrynnIcon name="Link" size={16} color="var(--color-primary)" weight="duotone" />
        </div>
        Related Tools
      </h2>
      <div className="grid gap-3 sm:grid-cols-2">
        {relatedTools.map((t) => {
          const fullTool = tools.find((x) => x.slug === t.slug && x.categorySlug === t.categorySlug);
          const cat = categories.find((c) => c.slug === t.categorySlug);
          const color = cat?.color ?? "var(--color-primary)";
          const iconName = fullTool?.icon ?? "Lightning";

          return (
            <a
              key={t.slug}
              href={`/${t.categorySlug}/${t.slug}`}
              className="group flex items-center gap-3 p-3.5 rounded-xl border border-border bg-muted hover:border-primary/30 transition-all duration-200"
            >
              <div className="w-10 h-10 shrink-0 rounded-lg flex items-center justify-center group-hover:scale-105 transition-transform" style={{ background: `${color}18` }}>
                <KrynnIcon name={iconName} size={20} weight="duotone" color={color} />
              </div>
              <div className="min-w-0 flex-1">
                <div className="font-medium text-sm text-foreground truncate group-hover:text-primary transition-colors">{t.name}</div>
                <div className="text-xs text-muted-foreground">Free Browser Tool</div>
              </div>
              <CaretRight size={14} className="text-muted-foreground group-hover:translate-x-0.5 transition-transform" />
            </a>
          );
        })}
      </div>
    </section>
  );
}

/* ── Tool Layout (main) ── */

interface ToolLayoutProps {
  title: string;
  subtitle: string;
  children: React.ReactNode;
  howToUse: string[];
  faq: FAQItem[];
  relatedTools: Array<{ name: string; slug: string; categorySlug: string }>;
  schema?: object;
  categorySlug?: string;
  toolSlug?: string;
  trustBadges?: TrustBadge[];
}

export function ToolLayout({
  title,
  subtitle,
  children,
  howToUse,
  faq,
  relatedTools,
  schema,
  categorySlug,
  toolSlug,
  trustBadges,
}: ToolLayoutProps) {
  const category = categorySlug ? categories.find((c) => c.slug === categorySlug) : undefined;
  const categoryName = category?.name ?? categorySlug;

  const effectiveHowToUse = useMemo(() => {
    if (howToUse && howToUse.length > 0) return howToUse;
    return [
      `Select or upload your input into the ${title} workspace above.`,
      `Configure settings or options to match your requirements.`,
      `Click the primary action button to process your request instantly.`,
      `Download or copy your result — 100% free, private, with zero watermarks.`,
    ];
  }, [howToUse, title]);

  const effectiveFaq = useMemo(() => {
    if (faq && faq.length > 0) return faq;
    return [
      {
        question: `Is ${title} completely free to use?`,
        answer: `Yes, ${title} on Krynn Tools is 100% free with no signup, no subscriptions, and no hidden limitations.`,
      },
      {
        question: `Are my files and data safe when using ${title}?`,
        answer: `Absolutely. ${title} operates entirely within your web browser using client-side Web APIs. Your data is never uploaded to external servers.`,
      },
      {
        question: `Do I need to download or install software for ${title}?`,
        answer: `No software installation or browser plugin is needed. ${title} runs instantly in any modern web browser.`,
      },
      {
        question: `Does ${title} work on mobile devices?`,
        answer: `Yes, ${title} is optimized for mobile phones, tablets, laptops, and desktop computers.`,
      },
    ];
  }, [faq, title]);

  const breadcrumbItems = [
    ...(categoryName ? [{ label: categoryName, href: `/${categorySlug}` }] : []),
    ...(toolSlug ? [{ label: title }] : []),
  ];

  return (
    <>
      {/* ── Hero ── */}
      <section className="relative overflow-hidden border-b border-border bg-muted">
        <div
          className="absolute pointer-events-none opacity-20 blur-[100px]"
          style={{
            top: "-30%", right: "-10%", width: "400px", height: "400px", borderRadius: "50%",
            background: `radial-gradient(circle, ${category?.color ?? "var(--color-primary)"} 0%, transparent 70%)`,
          }}
        />
        <div className="container-app relative z-10 py-8 sm:py-12 lg:py-16">
          {breadcrumbItems.length > 0 && <Breadcrumbs items={breadcrumbItems} />}

          <div className="mt-4 text-center max-w-2xl mx-auto">
            {category && (
              <span
                className="badge mb-4 text-xs font-semibold"
                style={{ backgroundColor: `${category.color}15`, color: category.color, borderColor: `${category.color}25` }}
              >
                <KrynnIcon name={category.icon} size={14} weight="duotone" color={category.color} />
                {category.name}
              </span>
            )}
            <h1 className="mb-3">{title}</h1>
            <p className="text-sm sm:text-base text-muted-foreground leading-relaxed">{subtitle}</p>
          </div>
        </div>
      </section>

      {/* ── Tool Workspace ── */}
      <section className="container-app py-8 sm:py-10 lg:py-12">
        <div className="max-w-3xl mx-auto space-y-6">
          <div className="workspace-card">{children}</div>
          <AdSlot position="below-tool" />
          <TrustStrip items={trustBadges} />
        </div>
      </section>

      {/* ── Secondary Sections ── */}
      <section className="border-t border-border bg-muted">
        <div className="container-app py-10 sm:py-14 lg:py-16 space-y-8 sm:space-y-10">
          <HowToUse steps={effectiveHowToUse} />
          <FAQ items={effectiveFaq} />
          {relatedTools.length > 0 && <RelatedTools tools={relatedTools} />}
          <UserReviews toolTitle={title} />

          {/* ── Trustpilot Review CTA ── */}
          <div className="rounded-2xl border border-border bg-card p-6 sm:p-8 text-center">
            <div className="flex justify-center gap-1 mb-3">
              {[1, 2, 3, 4, 5].map((s) => (
                <svg key={s} width="20" height="20" viewBox="0 0 24 24" fill={s <= 4 ? "#00b67a" : "#dcdce6"}>
                  <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z" />
                </svg>
              ))}
            </div>
            <h3 className="text-sm font-bold text-foreground mb-1">Enjoying {title}?</h3>
            <p className="text-xs text-muted-foreground mb-4">Share your experience on Trustpilot — it takes 30 seconds.</p>
            <a
              href="https://www.trustpilot.com/evaluate/krynntools.online"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 bg-[#00b67a] text-white px-5 py-2.5 rounded-full text-sm font-semibold hover:bg-[#009c6a] transition-colors"
            >
              <svg width="16" height="16" viewBox="0 0 24 24" fill="white">
                <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z" />
              </svg>
              Review us on Trustpilot
            </a>
          </div>
        </div>
      </section>

      {/* ── Schema.org ── */}
      {schema && (
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
      )}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "FAQPage",
            mainEntity: effectiveFaq.map((item) => ({
              "@type": "Question",
              name: item.question,
              acceptedAnswer: { "@type": "Answer", text: item.answer },
            })),
          }),
        }}
      />
      {/* BreadcrumbList Schema */}
      {breadcrumbItems.length > 0 && (
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "BreadcrumbList",
              itemListElement: [
                {
                  "@type": "ListItem",
                  position: 1,
                  name: "Home",
                  item: "https://www.krynntools.online",
                },
                ...breadcrumbItems.map((item, i) => ({
                  "@type": "ListItem",
                  position: i + 2,
                  name: item.label,
                  ...(item.href ? { item: `https://www.krynntools.online${item.href}` } : {}),
                })),
              ],
            }),
          }}
        />
      )}
      {/* HowTo Schema */}
      {effectiveHowToUse.length > 0 && (
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "HowTo",
              name: title,
              description: subtitle,
              step: effectiveHowToUse.map((step, i) => ({
                "@type": "HowToStep",
                position: i + 1,
                name: `Step ${i + 1}`,
                text: step,
              })),
            }),
          }}
        />
      )}

      <StickyMobileCTA label="Use This Tool" />
      <AdSlot position="mobile-anchor" />
    </>
  );
}

/* ── Reviews ── */

interface Review {
  id: string;
  author: string;
  rating: number;
  date: string;
  content: string;
}

export function UserReviews({ toolTitle }: { toolTitle: string }) {
  const [reviews, setReviews] = useState<Review[]>([]);
  const [name, setName] = useState("");
  const [rating, setRating] = useState(5);
  const [content, setContent] = useState("");
  const [submitted, setSubmitted] = useState(false);
  const [hoverRating, setHoverRating] = useState(0);

  useEffect(() => {
    const stored = localStorage.getItem(`reviews_${toolTitle}`);
    if (stored) {
      try { setReviews(JSON.parse(stored)); } catch { setReviews([]); }
    }
  }, [toolTitle]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!name.trim() || !content.trim()) return;
    const newReview: Review = { id: Date.now().toString(), author: name.trim(), rating, date: "Just now", content: content.trim() };
    const stored = localStorage.getItem(`reviews_${toolTitle}`);
    let storedList: Review[] = [];
    if (stored) { try { storedList = JSON.parse(stored); } catch {} }
    const updated = [newReview, ...storedList];
    localStorage.setItem(`reviews_${toolTitle}`, JSON.stringify(updated));
    setReviews(updated);
    setName(""); setRating(5); setContent(""); setSubmitted(true);
    setTimeout(() => setSubmitted(false), 3000);
  };

  const averageRating = useMemo(() => {
    if (reviews.length === 0) return "0.0";
    return (reviews.reduce((acc, r) => acc + r.rating, 0) / reviews.length).toFixed(1);
  }, [reviews]);

  const renderStars = (count: number, size = 16, onClick?: (r: number) => void) => (
    <div className="flex gap-0.5">
      {[1, 2, 3, 4, 5].map((star) => (
        <Star
          key={star}
          size={size}
          weight={star <= count ? "fill" : "regular"}
          className={`${onClick ? "cursor-pointer" : ""} transition-colors duration-150`}
          style={{ color: star <= count ? "#FBBF24" : "currentColor" }}
          onClick={() => onClick?.(star)}
        />
      ))}
    </div>
  );

  return (
    <section className="rounded-2xl border border-border bg-card p-6 sm:p-8">
      <div className="flex flex-col md:flex-row md:items-start justify-between gap-6 mb-6">
        <div>
          <h2 className="text-lg font-bold mb-1 flex items-center gap-2">
            <div className="w-6 h-6 rounded-md bg-primary/10 flex items-center justify-center">
              <KrynnIcon name="Chat" size={16} color="var(--color-primary)" weight="duotone" />
            </div>
            User Reviews
          </h2>
          <p className="text-xs text-muted-foreground">Submit a review below. No signup needed.</p>
        </div>
        {reviews.length > 0 && (
          <div className="flex items-center gap-4 bg-muted px-4 py-2.5 rounded-xl border border-border self-start">
            <div className="text-center">
              <span className="block text-2xl font-extrabold leading-none">{averageRating}</span>
              <span className="text-[10px] uppercase font-bold text-muted-foreground tracking-wider mt-1 block">out of 5</span>
            </div>
            <div className="h-8 w-px bg-border" />
            <div>
              {renderStars(Math.round(parseFloat(averageRating)), 14)}
              <span className="text-[10px] font-semibold text-muted-foreground mt-0.5 block">{reviews.length} review{reviews.length !== 1 ? "s" : ""}</span>
            </div>
          </div>
        )}
      </div>

      {reviews.length > 0 && (
        <div className="space-y-3 mb-6 max-h-[280px] overflow-y-auto pr-2 custom-scrollbar">
          {reviews.map((review) => (
            <div key={review.id} className="p-4 rounded-xl border border-border bg-muted">
              <div className="flex justify-between items-center mb-2">
                <div className="flex items-center gap-2">
                  <span className="w-8 h-8 rounded-full bg-primary/10 text-primary flex items-center justify-center font-bold text-xs border border-border">
                    {review.author[0].toUpperCase()}
                  </span>
                  <div>
                    <span className="block text-sm font-bold leading-snug">{review.author}</span>
                    <span className="block text-[10px] text-muted-foreground">{review.date}</span>
                  </div>
                </div>
                {renderStars(review.rating, 12)}
              </div>
              <p className="text-sm text-foreground leading-relaxed">{review.content}</p>
            </div>
          ))}
        </div>
      )}

      {reviews.length === 0 && (
        <p className="text-sm text-muted-foreground mb-6">No reviews yet. Be the first to share your experience!</p>
      )}

      <div className="bg-muted p-5 rounded-xl border border-border">
        <h3 className="text-sm font-bold mb-1">Share your experience</h3>
        <p className="text-xs text-muted-foreground mb-4">No signup needed. Updates instantly.</p>
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="flex flex-col sm:flex-row sm:items-center gap-4">
            <div className="flex-1">
              <label className="block text-[10px] font-bold uppercase tracking-wider text-muted-foreground mb-1">Your Name</label>
              <input type="text" placeholder="e.g. John Doe" value={name} onChange={(e) => setName(e.target.value)} required />
            </div>
            <div>
              <label className="block text-[10px] font-bold uppercase tracking-wider text-muted-foreground mb-1">Rating</label>
              <div className="py-2 flex items-center gap-0.5">
                {[1, 2, 3, 4, 5].map((star) => (
                  <button key={star} type="button" onClick={() => setRating(star)} onMouseEnter={() => setHoverRating(star)} onMouseLeave={() => setHoverRating(0)} className="p-0.5 outline-none focus:scale-110 transition-transform" aria-label={`Rate ${star} star${star > 1 ? "s" : ""}`}>
                    <Star size={20} weight={star <= (hoverRating || rating) ? "fill" : "regular"} style={{ color: star <= (hoverRating || rating) ? "#FBBF24" : "currentColor" }} className="cursor-pointer" />
                  </button>
                ))}
              </div>
            </div>
          </div>
          <div>
            <label className="block text-[10px] font-bold uppercase tracking-wider text-muted-foreground mb-1">Comment</label>
            <textarea placeholder="What did you use this tool for?" value={content} onChange={(e) => setContent(e.target.value)} required rows={3} className="resize-none" />
          </div>
          <div className="flex items-center justify-between">
            <button type="submit" className="btn-primary py-2 px-6 text-sm font-semibold">Submit Feedback</button>
            {submitted && (
              <span className="text-xs text-success font-bold flex items-center gap-1">
                <CheckCircle size={16} /> Posted!
              </span>
            )}
          </div>
        </form>
      </div>
    </section>
  );
}
